/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BankAccountsDashboardReportEntity,
  ExceptionResponseEntity,
} from '../models/index';
import {
    BankAccountsDashboardReportEntityFromJSON,
    BankAccountsDashboardReportEntityToJSON,
    ExceptionResponseEntityFromJSON,
    ExceptionResponseEntityToJSON,
} from '../models/index';

export interface GetBankAccountsReportRequest {
    account?: string;
    amountFrom?: string;
    amountTo?: string;
    amountType?: GetBankAccountsReportAmountTypeEnum;
    cashDateFrom?: string;
    cashDateTo?: string;
    competenceDateFrom?: string;
    competenceDateTo?: string;
    completed?: string;
    contact?: string;
    createdAtFrom?: string;
    createdAtTo?: string;
    direction?: GetBankAccountsReportDirectionEnum;
    dueDateFrom?: string;
    dueDateTo?: string;
    finalAmountFrom?: string;
    finalAmountTo?: string;
    installmentFinancialRecord?: string;
    recurringFinancialRecord?: string;
    reconciled?: string;
    subcategory?: string;
    tags?: string;
}

/**
 * BankAccountsApi - interface
 * 
 * @export
 * @interface BankAccountsApiInterface
 */
export interface BankAccountsApiInterface {
    /**
     * 
     * @summary Gera relatório de contas bancárias
     * @param {string} [account] Identificadores das contas separadas por vírgula
     * @param {string} [amountFrom] Valor do lançamento mínimo.
     * @param {string} [amountTo] Valor do lançamento máximo.
     * @param {'base' | 'final'} [amountType] Tipo de valor a ser utilizado nos cálculos. \&quot;base\&quot; para amount, \&quot;final\&quot; para finalAmount. Padrão é \&quot;final\&quot;.
     * @param {string} [cashDateFrom] Data inicial do caixa
     * @param {string} [cashDateTo] Data final do caixa
     * @param {string} [competenceDateFrom] Data inicial da competência
     * @param {string} [competenceDateTo] Data final da competência
     * @param {string} [completed] Status de conclusão dos lançamentos
     * @param {string} [contact] ID do contato
     * @param {string} [createdAtFrom] Data inicial da criação
     * @param {string} [createdAtTo] Data final da criação
     * @param {'IN' | 'OUT'} [direction] Direção do relatório
     * @param {string} [dueDateFrom] Data inicial do vencimento
     * @param {string} [dueDateTo] Data final do vencimento
     * @param {string} [finalAmountFrom] Valor final do lançamento mínimo.
     * @param {string} [finalAmountTo] Valor final do lançamento máximo.
     * @param {string} [installmentFinancialRecord] ID do lançamento financeiro recorrente
     * @param {string} [recurringFinancialRecord] ID do lançamento financeiro recorrente
     * @param {string} [reconciled] Status de conciliação
     * @param {string} [subcategory] ID da subcategoria
     * @param {string} [tags] IDs das tags
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BankAccountsApiInterface
     */
    getBankAccountsReportRaw(requestParameters: GetBankAccountsReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BankAccountsDashboardReportEntity>>;

    /**
     * Gera relatório de contas bancárias
     */
    getBankAccountsReport(requestParameters: GetBankAccountsReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BankAccountsDashboardReportEntity>;

}

/**
 * 
 */
export class BankAccountsApi extends runtime.BaseAPI implements BankAccountsApiInterface {

    /**
     * Gera relatório de contas bancárias
     */
    async getBankAccountsReportRaw(requestParameters: GetBankAccountsReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BankAccountsDashboardReportEntity>> {
        const queryParameters: any = {};

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        if (requestParameters['amountFrom'] != null) {
            queryParameters['amountFrom'] = requestParameters['amountFrom'];
        }

        if (requestParameters['amountTo'] != null) {
            queryParameters['amountTo'] = requestParameters['amountTo'];
        }

        if (requestParameters['amountType'] != null) {
            queryParameters['amountType'] = requestParameters['amountType'];
        }

        if (requestParameters['cashDateFrom'] != null) {
            queryParameters['cashDateFrom'] = requestParameters['cashDateFrom'];
        }

        if (requestParameters['cashDateTo'] != null) {
            queryParameters['cashDateTo'] = requestParameters['cashDateTo'];
        }

        if (requestParameters['competenceDateFrom'] != null) {
            queryParameters['competenceDateFrom'] = requestParameters['competenceDateFrom'];
        }

        if (requestParameters['competenceDateTo'] != null) {
            queryParameters['competenceDateTo'] = requestParameters['competenceDateTo'];
        }

        if (requestParameters['completed'] != null) {
            queryParameters['completed'] = requestParameters['completed'];
        }

        if (requestParameters['contact'] != null) {
            queryParameters['contact'] = requestParameters['contact'];
        }

        if (requestParameters['createdAtFrom'] != null) {
            queryParameters['createdAtFrom'] = requestParameters['createdAtFrom'];
        }

        if (requestParameters['createdAtTo'] != null) {
            queryParameters['createdAtTo'] = requestParameters['createdAtTo'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['dueDateFrom'] != null) {
            queryParameters['dueDateFrom'] = requestParameters['dueDateFrom'];
        }

        if (requestParameters['dueDateTo'] != null) {
            queryParameters['dueDateTo'] = requestParameters['dueDateTo'];
        }

        if (requestParameters['finalAmountFrom'] != null) {
            queryParameters['finalAmountFrom'] = requestParameters['finalAmountFrom'];
        }

        if (requestParameters['finalAmountTo'] != null) {
            queryParameters['finalAmountTo'] = requestParameters['finalAmountTo'];
        }

        if (requestParameters['installmentFinancialRecord'] != null) {
            queryParameters['installmentFinancialRecord'] = requestParameters['installmentFinancialRecord'];
        }

        if (requestParameters['recurringFinancialRecord'] != null) {
            queryParameters['recurringFinancialRecord'] = requestParameters['recurringFinancialRecord'];
        }

        if (requestParameters['reconciled'] != null) {
            queryParameters['reconciled'] = requestParameters['reconciled'];
        }

        if (requestParameters['subcategory'] != null) {
            queryParameters['subcategory'] = requestParameters['subcategory'];
        }

        if (requestParameters['tags'] != null) {
            queryParameters['tags'] = requestParameters['tags'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/external/bank-accounts/report`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BankAccountsDashboardReportEntityFromJSON(jsonValue));
    }

    /**
     * Gera relatório de contas bancárias
     */
    async getBankAccountsReport(requestParameters: GetBankAccountsReportRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BankAccountsDashboardReportEntity> {
        const response = await this.getBankAccountsReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetBankAccountsReportAmountTypeEnum = {
    Base: 'base',
    Final: 'final'
} as const;
export type GetBankAccountsReportAmountTypeEnum = typeof GetBankAccountsReportAmountTypeEnum[keyof typeof GetBankAccountsReportAmountTypeEnum];
/**
 * @export
 */
export const GetBankAccountsReportDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type GetBankAccountsReportDirectionEnum = typeof GetBankAccountsReportDirectionEnum[keyof typeof GetBankAccountsReportDirectionEnum];
