/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CashFlowReportEntity,
} from '../models/index';
import {
    CashFlowReportEntityFromJSON,
    CashFlowReportEntityToJSON,
} from '../models/index';

export interface GenerateCashFlowReportRequest {
    tags: string;
    reconciled: string;
    bankAccount: string;
    periodTo: string;
    periodFrom: string;
    grouping: GenerateCashFlowReportGroupingEnum;
}

/**
 * CashFlowReportsApi - interface
 * 
 * @export
 * @interface CashFlowReportsApiInterface
 */
export interface CashFlowReportsApiInterface {
    /**
     * 
     * @summary Gera um relatório de fluxo de caixa
     * @param {string} tags IDs das tags
     * @param {string} reconciled Status de conciliação
     * @param {string} bankAccount ID da conta bancária
     * @param {string} periodTo Data final do período
     * @param {string} periodFrom Data inicial do período
     * @param {'daily' | 'weekly' | 'monthly' | 'annual'} grouping Agrupamento do relatório
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowReportsApiInterface
     */
    generateCashFlowReportRaw(requestParameters: GenerateCashFlowReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CashFlowReportEntity>>;

    /**
     * Gera um relatório de fluxo de caixa
     */
    generateCashFlowReport(requestParameters: GenerateCashFlowReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CashFlowReportEntity>;

}

/**
 * 
 */
export class CashFlowReportsApi extends runtime.BaseAPI implements CashFlowReportsApiInterface {

    /**
     * Gera um relatório de fluxo de caixa
     */
    async generateCashFlowReportRaw(requestParameters: GenerateCashFlowReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CashFlowReportEntity>> {
        if (requestParameters['tags'] == null) {
            throw new runtime.RequiredError(
                'tags',
                'Required parameter "tags" was null or undefined when calling generateCashFlowReport().'
            );
        }

        if (requestParameters['reconciled'] == null) {
            throw new runtime.RequiredError(
                'reconciled',
                'Required parameter "reconciled" was null or undefined when calling generateCashFlowReport().'
            );
        }

        if (requestParameters['bankAccount'] == null) {
            throw new runtime.RequiredError(
                'bankAccount',
                'Required parameter "bankAccount" was null or undefined when calling generateCashFlowReport().'
            );
        }

        if (requestParameters['periodTo'] == null) {
            throw new runtime.RequiredError(
                'periodTo',
                'Required parameter "periodTo" was null or undefined when calling generateCashFlowReport().'
            );
        }

        if (requestParameters['periodFrom'] == null) {
            throw new runtime.RequiredError(
                'periodFrom',
                'Required parameter "periodFrom" was null or undefined when calling generateCashFlowReport().'
            );
        }

        if (requestParameters['grouping'] == null) {
            throw new runtime.RequiredError(
                'grouping',
                'Required parameter "grouping" was null or undefined when calling generateCashFlowReport().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['tags'] != null) {
            queryParameters['tags'] = requestParameters['tags'];
        }

        if (requestParameters['reconciled'] != null) {
            queryParameters['reconciled'] = requestParameters['reconciled'];
        }

        if (requestParameters['bankAccount'] != null) {
            queryParameters['bankAccount'] = requestParameters['bankAccount'];
        }

        if (requestParameters['periodTo'] != null) {
            queryParameters['periodTo'] = requestParameters['periodTo'];
        }

        if (requestParameters['periodFrom'] != null) {
            queryParameters['periodFrom'] = requestParameters['periodFrom'];
        }

        if (requestParameters['grouping'] != null) {
            queryParameters['grouping'] = requestParameters['grouping'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/external/cash-flow/report`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CashFlowReportEntityFromJSON(jsonValue));
    }

    /**
     * Gera um relatório de fluxo de caixa
     */
    async generateCashFlowReport(requestParameters: GenerateCashFlowReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CashFlowReportEntity> {
        const response = await this.generateCashFlowReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GenerateCashFlowReportGroupingEnum = {
    Daily: 'daily',
    Weekly: 'weekly',
    Monthly: 'monthly',
    Annual: 'annual'
} as const;
export type GenerateCashFlowReportGroupingEnum = typeof GenerateCashFlowReportGroupingEnum[keyof typeof GenerateCashFlowReportGroupingEnum];
