/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AggregatedFinancialRecordsReportEntity,
  ExceptionResponseEntity,
  FinancialRecordsAggregatedResultReportEntity,
  MonthlyFinancialReportEntity,
} from '../models/index';
import {
    AggregatedFinancialRecordsReportEntityFromJSON,
    AggregatedFinancialRecordsReportEntityToJSON,
    ExceptionResponseEntityFromJSON,
    ExceptionResponseEntityToJSON,
    FinancialRecordsAggregatedResultReportEntityFromJSON,
    FinancialRecordsAggregatedResultReportEntityToJSON,
    MonthlyFinancialReportEntityFromJSON,
    MonthlyFinancialReportEntityToJSON,
} from '../models/index';

export interface GenerateAggregatedFinancialRecordsReportRequest {
    aggregationDirection: GenerateAggregatedFinancialRecordsReportAggregationDirectionEnum;
    groupBy: GenerateAggregatedFinancialRecordsReportGroupByEnum;
    account?: string;
    amountFrom?: string;
    amountTo?: string;
    amountType?: GenerateAggregatedFinancialRecordsReportAmountTypeEnum;
    cashDateFrom?: string;
    cashDateTo?: string;
    competenceDateFrom?: string;
    competenceDateTo?: string;
    completed?: string;
    contact?: string;
    createdAtFrom?: string;
    createdAtTo?: string;
    direction?: GenerateAggregatedFinancialRecordsReportDirectionEnum;
    dueDateFrom?: string;
    dueDateTo?: string;
    finalAmountFrom?: string;
    finalAmountTo?: string;
    installmentFinancialRecord?: string;
    recurringFinancialRecord?: string;
    reconciled?: string;
    subcategory?: string;
    tags?: string;
    sortOrder?: GenerateAggregatedFinancialRecordsReportSortOrderEnum;
}

export interface GenerateMonthlyFinancialReportRequest {
    account?: string;
    amountFrom?: string;
    amountTo?: string;
    amountType?: GenerateMonthlyFinancialReportAmountTypeEnum;
    cashDateFrom?: string;
    cashDateTo?: string;
    competenceDateFrom?: string;
    competenceDateTo?: string;
    completed?: string;
    contact?: string;
    createdAtFrom?: string;
    createdAtTo?: string;
    direction?: GenerateMonthlyFinancialReportDirectionEnum;
    dueDateFrom?: string;
    dueDateTo?: string;
    finalAmountFrom?: string;
    finalAmountTo?: string;
    installmentFinancialRecord?: string;
    recurringFinancialRecord?: string;
    reconciled?: string;
    subcategory?: string;
    tags?: string;
}

export interface GetAggregatedResultReportRequest {
    account?: string;
    amountFrom?: string;
    amountTo?: string;
    amountType?: GetAggregatedResultReportAmountTypeEnum;
    cashDateFrom?: string;
    cashDateTo?: string;
    competenceDateFrom?: string;
    competenceDateTo?: string;
    completed?: string;
    contact?: string;
    createdAtFrom?: string;
    createdAtTo?: string;
    direction?: GetAggregatedResultReportDirectionEnum;
    dueDateFrom?: string;
    dueDateTo?: string;
    finalAmountFrom?: string;
    finalAmountTo?: string;
    installmentFinancialRecord?: string;
    recurringFinancialRecord?: string;
    reconciled?: string;
    subcategory?: string;
    tags?: string;
}

export interface SystemGetAggregatedResultReportRequest {
    account?: string;
    amountFrom?: string;
    amountTo?: string;
    amountType?: SystemGetAggregatedResultReportAmountTypeEnum;
    cashDateFrom?: string;
    cashDateTo?: string;
    competenceDateFrom?: string;
    competenceDateTo?: string;
    completed?: string;
    contact?: string;
    createdAtFrom?: string;
    createdAtTo?: string;
    direction?: SystemGetAggregatedResultReportDirectionEnum;
    dueDateFrom?: string;
    dueDateTo?: string;
    finalAmountFrom?: string;
    finalAmountTo?: string;
    installmentFinancialRecord?: string;
    recurringFinancialRecord?: string;
    reconciled?: string;
    subcategory?: string;
    tags?: string;
}

/**
 * FinancialRecordsReportsApi - interface
 * 
 * @export
 * @interface FinancialRecordsReportsApiInterface
 */
export interface FinancialRecordsReportsApiInterface {
    /**
     * 
     * @summary Gera relatório de lançamentos financeiros agregados por categoria, contato ou tag
     * @param {'IN' | 'OUT'} aggregationDirection Direção do lançamento financeiro
     * @param {'category' | 'contact' | 'tag'} groupBy Campo para agrupamento dos dados
     * @param {string} [account] Identificadores das contas separadas por vírgula
     * @param {string} [amountFrom] Valor do lançamento mínimo.
     * @param {string} [amountTo] Valor do lançamento máximo.
     * @param {'base' | 'final'} [amountType] Tipo de valor a ser utilizado nos cálculos. \&quot;base\&quot; para amount, \&quot;final\&quot; para finalAmount. Padrão é \&quot;final\&quot;.
     * @param {string} [cashDateFrom] Data inicial do caixa
     * @param {string} [cashDateTo] Data final do caixa
     * @param {string} [competenceDateFrom] Data inicial da competência
     * @param {string} [competenceDateTo] Data final da competência
     * @param {string} [completed] Status de conclusão dos lançamentos
     * @param {string} [contact] ID do contato
     * @param {string} [createdAtFrom] Data inicial da criação
     * @param {string} [createdAtTo] Data final da criação
     * @param {'IN' | 'OUT'} [direction] Direção do relatório
     * @param {string} [dueDateFrom] Data inicial do vencimento
     * @param {string} [dueDateTo] Data final do vencimento
     * @param {string} [finalAmountFrom] Valor final do lançamento mínimo.
     * @param {string} [finalAmountTo] Valor final do lançamento máximo.
     * @param {string} [installmentFinancialRecord] ID do lançamento financeiro recorrente
     * @param {string} [recurringFinancialRecord] ID do lançamento financeiro recorrente
     * @param {string} [reconciled] Status de conciliação
     * @param {string} [subcategory] ID da subcategoria
     * @param {string} [tags] IDs das tags
     * @param {'asc' | 'desc'} [sortOrder] Ordem de classificação
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FinancialRecordsReportsApiInterface
     */
    generateAggregatedFinancialRecordsReportRaw(requestParameters: GenerateAggregatedFinancialRecordsReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AggregatedFinancialRecordsReportEntity>>;

    /**
     * Gera relatório de lançamentos financeiros agregados por categoria, contato ou tag
     */
    generateAggregatedFinancialRecordsReport(requestParameters: GenerateAggregatedFinancialRecordsReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AggregatedFinancialRecordsReportEntity>;

    /**
     * 
     * @summary Gera relatório financeiro mensal para os últimos 12 meses
     * @param {string} [account] Identificadores das contas separadas por vírgula
     * @param {string} [amountFrom] Valor do lançamento mínimo.
     * @param {string} [amountTo] Valor do lançamento máximo.
     * @param {'base' | 'final'} [amountType] Tipo de valor a ser utilizado nos cálculos. \&quot;base\&quot; para amount, \&quot;final\&quot; para finalAmount. Padrão é \&quot;final\&quot;.
     * @param {string} [cashDateFrom] Data inicial do caixa
     * @param {string} [cashDateTo] Data final do caixa
     * @param {string} [competenceDateFrom] Data inicial da competência
     * @param {string} [competenceDateTo] Data final da competência
     * @param {string} [completed] Status de conclusão dos lançamentos
     * @param {string} [contact] ID do contato
     * @param {string} [createdAtFrom] Data inicial da criação
     * @param {string} [createdAtTo] Data final da criação
     * @param {'IN' | 'OUT'} [direction] Direção do relatório
     * @param {string} [dueDateFrom] Data inicial do vencimento
     * @param {string} [dueDateTo] Data final do vencimento
     * @param {string} [finalAmountFrom] Valor final do lançamento mínimo.
     * @param {string} [finalAmountTo] Valor final do lançamento máximo.
     * @param {string} [installmentFinancialRecord] ID do lançamento financeiro recorrente
     * @param {string} [recurringFinancialRecord] ID do lançamento financeiro recorrente
     * @param {string} [reconciled] Status de conciliação
     * @param {string} [subcategory] ID da subcategoria
     * @param {string} [tags] IDs das tags
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FinancialRecordsReportsApiInterface
     */
    generateMonthlyFinancialReportRaw(requestParameters: GenerateMonthlyFinancialReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MonthlyFinancialReportEntity>>;

    /**
     * Gera relatório financeiro mensal para os últimos 12 meses
     */
    generateMonthlyFinancialReport(requestParameters: GenerateMonthlyFinancialReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MonthlyFinancialReportEntity>;

    /**
     * 
     * @summary Get aggregated result report for financial records
     * @param {string} [account] Identificadores das contas separadas por vírgula
     * @param {string} [amountFrom] Valor do lançamento mínimo.
     * @param {string} [amountTo] Valor do lançamento máximo.
     * @param {'base' | 'final'} [amountType] Tipo de valor a ser utilizado nos cálculos. \&quot;base\&quot; para amount, \&quot;final\&quot; para finalAmount. Padrão é \&quot;final\&quot;.
     * @param {string} [cashDateFrom] Data inicial do caixa
     * @param {string} [cashDateTo] Data final do caixa
     * @param {string} [competenceDateFrom] Data inicial da competência
     * @param {string} [competenceDateTo] Data final da competência
     * @param {string} [completed] Status de conclusão dos lançamentos
     * @param {string} [contact] ID do contato
     * @param {string} [createdAtFrom] Data inicial da criação
     * @param {string} [createdAtTo] Data final da criação
     * @param {'IN' | 'OUT'} [direction] Direção do relatório
     * @param {string} [dueDateFrom] Data inicial do vencimento
     * @param {string} [dueDateTo] Data final do vencimento
     * @param {string} [finalAmountFrom] Valor final do lançamento mínimo.
     * @param {string} [finalAmountTo] Valor final do lançamento máximo.
     * @param {string} [installmentFinancialRecord] ID do lançamento financeiro recorrente
     * @param {string} [recurringFinancialRecord] ID do lançamento financeiro recorrente
     * @param {string} [reconciled] Status de conciliação
     * @param {string} [subcategory] ID da subcategoria
     * @param {string} [tags] IDs das tags
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FinancialRecordsReportsApiInterface
     */
    getAggregatedResultReportRaw(requestParameters: GetAggregatedResultReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FinancialRecordsAggregatedResultReportEntity>>;

    /**
     * Get aggregated result report for financial records
     */
    getAggregatedResultReport(requestParameters: GetAggregatedResultReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FinancialRecordsAggregatedResultReportEntity>;

    /**
     * 
     * @summary Get aggregated   result report for financial records
     * @param {string} [account] Identificadores das contas separadas por vírgula
     * @param {string} [amountFrom] Valor do lançamento mínimo.
     * @param {string} [amountTo] Valor do lançamento máximo.
     * @param {'base' | 'final'} [amountType] Tipo de valor a ser utilizado nos cálculos. \&quot;base\&quot; para amount, \&quot;final\&quot; para finalAmount. Padrão é \&quot;final\&quot;.
     * @param {string} [cashDateFrom] Data inicial do caixa
     * @param {string} [cashDateTo] Data final do caixa
     * @param {string} [competenceDateFrom] Data inicial da competência
     * @param {string} [competenceDateTo] Data final da competência
     * @param {string} [completed] Status de conclusão dos lançamentos
     * @param {string} [contact] ID do contato
     * @param {string} [createdAtFrom] Data inicial da criação
     * @param {string} [createdAtTo] Data final da criação
     * @param {'IN' | 'OUT'} [direction] Direção do relatório
     * @param {string} [dueDateFrom] Data inicial do vencimento
     * @param {string} [dueDateTo] Data final do vencimento
     * @param {string} [finalAmountFrom] Valor final do lançamento mínimo.
     * @param {string} [finalAmountTo] Valor final do lançamento máximo.
     * @param {string} [installmentFinancialRecord] ID do lançamento financeiro recorrente
     * @param {string} [recurringFinancialRecord] ID do lançamento financeiro recorrente
     * @param {string} [reconciled] Status de conciliação
     * @param {string} [subcategory] ID da subcategoria
     * @param {string} [tags] IDs das tags
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FinancialRecordsReportsApiInterface
     */
    systemGetAggregatedResultReportRaw(requestParameters: SystemGetAggregatedResultReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FinancialRecordsAggregatedResultReportEntity>>;

    /**
     * Get aggregated   result report for financial records
     */
    systemGetAggregatedResultReport(requestParameters: SystemGetAggregatedResultReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FinancialRecordsAggregatedResultReportEntity>;

}

/**
 * 
 */
export class FinancialRecordsReportsApi extends runtime.BaseAPI implements FinancialRecordsReportsApiInterface {

    /**
     * Gera relatório de lançamentos financeiros agregados por categoria, contato ou tag
     */
    async generateAggregatedFinancialRecordsReportRaw(requestParameters: GenerateAggregatedFinancialRecordsReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AggregatedFinancialRecordsReportEntity>> {
        if (requestParameters['aggregationDirection'] == null) {
            throw new runtime.RequiredError(
                'aggregationDirection',
                'Required parameter "aggregationDirection" was null or undefined when calling generateAggregatedFinancialRecordsReport().'
            );
        }

        if (requestParameters['groupBy'] == null) {
            throw new runtime.RequiredError(
                'groupBy',
                'Required parameter "groupBy" was null or undefined when calling generateAggregatedFinancialRecordsReport().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        if (requestParameters['amountFrom'] != null) {
            queryParameters['amountFrom'] = requestParameters['amountFrom'];
        }

        if (requestParameters['amountTo'] != null) {
            queryParameters['amountTo'] = requestParameters['amountTo'];
        }

        if (requestParameters['amountType'] != null) {
            queryParameters['amountType'] = requestParameters['amountType'];
        }

        if (requestParameters['cashDateFrom'] != null) {
            queryParameters['cashDateFrom'] = requestParameters['cashDateFrom'];
        }

        if (requestParameters['cashDateTo'] != null) {
            queryParameters['cashDateTo'] = requestParameters['cashDateTo'];
        }

        if (requestParameters['competenceDateFrom'] != null) {
            queryParameters['competenceDateFrom'] = requestParameters['competenceDateFrom'];
        }

        if (requestParameters['competenceDateTo'] != null) {
            queryParameters['competenceDateTo'] = requestParameters['competenceDateTo'];
        }

        if (requestParameters['completed'] != null) {
            queryParameters['completed'] = requestParameters['completed'];
        }

        if (requestParameters['contact'] != null) {
            queryParameters['contact'] = requestParameters['contact'];
        }

        if (requestParameters['createdAtFrom'] != null) {
            queryParameters['createdAtFrom'] = requestParameters['createdAtFrom'];
        }

        if (requestParameters['createdAtTo'] != null) {
            queryParameters['createdAtTo'] = requestParameters['createdAtTo'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['dueDateFrom'] != null) {
            queryParameters['dueDateFrom'] = requestParameters['dueDateFrom'];
        }

        if (requestParameters['dueDateTo'] != null) {
            queryParameters['dueDateTo'] = requestParameters['dueDateTo'];
        }

        if (requestParameters['finalAmountFrom'] != null) {
            queryParameters['finalAmountFrom'] = requestParameters['finalAmountFrom'];
        }

        if (requestParameters['finalAmountTo'] != null) {
            queryParameters['finalAmountTo'] = requestParameters['finalAmountTo'];
        }

        if (requestParameters['installmentFinancialRecord'] != null) {
            queryParameters['installmentFinancialRecord'] = requestParameters['installmentFinancialRecord'];
        }

        if (requestParameters['recurringFinancialRecord'] != null) {
            queryParameters['recurringFinancialRecord'] = requestParameters['recurringFinancialRecord'];
        }

        if (requestParameters['reconciled'] != null) {
            queryParameters['reconciled'] = requestParameters['reconciled'];
        }

        if (requestParameters['subcategory'] != null) {
            queryParameters['subcategory'] = requestParameters['subcategory'];
        }

        if (requestParameters['tags'] != null) {
            queryParameters['tags'] = requestParameters['tags'];
        }

        if (requestParameters['sortOrder'] != null) {
            queryParameters['sortOrder'] = requestParameters['sortOrder'];
        }

        if (requestParameters['aggregationDirection'] != null) {
            queryParameters['aggregationDirection'] = requestParameters['aggregationDirection'];
        }

        if (requestParameters['groupBy'] != null) {
            queryParameters['groupBy'] = requestParameters['groupBy'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/external/financial-records/aggregated/report`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AggregatedFinancialRecordsReportEntityFromJSON(jsonValue));
    }

    /**
     * Gera relatório de lançamentos financeiros agregados por categoria, contato ou tag
     */
    async generateAggregatedFinancialRecordsReport(requestParameters: GenerateAggregatedFinancialRecordsReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AggregatedFinancialRecordsReportEntity> {
        const response = await this.generateAggregatedFinancialRecordsReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gera relatório financeiro mensal para os últimos 12 meses
     */
    async generateMonthlyFinancialReportRaw(requestParameters: GenerateMonthlyFinancialReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MonthlyFinancialReportEntity>> {
        const queryParameters: any = {};

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        if (requestParameters['amountFrom'] != null) {
            queryParameters['amountFrom'] = requestParameters['amountFrom'];
        }

        if (requestParameters['amountTo'] != null) {
            queryParameters['amountTo'] = requestParameters['amountTo'];
        }

        if (requestParameters['amountType'] != null) {
            queryParameters['amountType'] = requestParameters['amountType'];
        }

        if (requestParameters['cashDateFrom'] != null) {
            queryParameters['cashDateFrom'] = requestParameters['cashDateFrom'];
        }

        if (requestParameters['cashDateTo'] != null) {
            queryParameters['cashDateTo'] = requestParameters['cashDateTo'];
        }

        if (requestParameters['competenceDateFrom'] != null) {
            queryParameters['competenceDateFrom'] = requestParameters['competenceDateFrom'];
        }

        if (requestParameters['competenceDateTo'] != null) {
            queryParameters['competenceDateTo'] = requestParameters['competenceDateTo'];
        }

        if (requestParameters['completed'] != null) {
            queryParameters['completed'] = requestParameters['completed'];
        }

        if (requestParameters['contact'] != null) {
            queryParameters['contact'] = requestParameters['contact'];
        }

        if (requestParameters['createdAtFrom'] != null) {
            queryParameters['createdAtFrom'] = requestParameters['createdAtFrom'];
        }

        if (requestParameters['createdAtTo'] != null) {
            queryParameters['createdAtTo'] = requestParameters['createdAtTo'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['dueDateFrom'] != null) {
            queryParameters['dueDateFrom'] = requestParameters['dueDateFrom'];
        }

        if (requestParameters['dueDateTo'] != null) {
            queryParameters['dueDateTo'] = requestParameters['dueDateTo'];
        }

        if (requestParameters['finalAmountFrom'] != null) {
            queryParameters['finalAmountFrom'] = requestParameters['finalAmountFrom'];
        }

        if (requestParameters['finalAmountTo'] != null) {
            queryParameters['finalAmountTo'] = requestParameters['finalAmountTo'];
        }

        if (requestParameters['installmentFinancialRecord'] != null) {
            queryParameters['installmentFinancialRecord'] = requestParameters['installmentFinancialRecord'];
        }

        if (requestParameters['recurringFinancialRecord'] != null) {
            queryParameters['recurringFinancialRecord'] = requestParameters['recurringFinancialRecord'];
        }

        if (requestParameters['reconciled'] != null) {
            queryParameters['reconciled'] = requestParameters['reconciled'];
        }

        if (requestParameters['subcategory'] != null) {
            queryParameters['subcategory'] = requestParameters['subcategory'];
        }

        if (requestParameters['tags'] != null) {
            queryParameters['tags'] = requestParameters['tags'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/external/financial-records/aggregated-monthly/report`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MonthlyFinancialReportEntityFromJSON(jsonValue));
    }

    /**
     * Gera relatório financeiro mensal para os últimos 12 meses
     */
    async generateMonthlyFinancialReport(requestParameters: GenerateMonthlyFinancialReportRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MonthlyFinancialReportEntity> {
        const response = await this.generateMonthlyFinancialReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get aggregated result report for financial records
     */
    async getAggregatedResultReportRaw(requestParameters: GetAggregatedResultReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FinancialRecordsAggregatedResultReportEntity>> {
        const queryParameters: any = {};

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        if (requestParameters['amountFrom'] != null) {
            queryParameters['amountFrom'] = requestParameters['amountFrom'];
        }

        if (requestParameters['amountTo'] != null) {
            queryParameters['amountTo'] = requestParameters['amountTo'];
        }

        if (requestParameters['amountType'] != null) {
            queryParameters['amountType'] = requestParameters['amountType'];
        }

        if (requestParameters['cashDateFrom'] != null) {
            queryParameters['cashDateFrom'] = requestParameters['cashDateFrom'];
        }

        if (requestParameters['cashDateTo'] != null) {
            queryParameters['cashDateTo'] = requestParameters['cashDateTo'];
        }

        if (requestParameters['competenceDateFrom'] != null) {
            queryParameters['competenceDateFrom'] = requestParameters['competenceDateFrom'];
        }

        if (requestParameters['competenceDateTo'] != null) {
            queryParameters['competenceDateTo'] = requestParameters['competenceDateTo'];
        }

        if (requestParameters['completed'] != null) {
            queryParameters['completed'] = requestParameters['completed'];
        }

        if (requestParameters['contact'] != null) {
            queryParameters['contact'] = requestParameters['contact'];
        }

        if (requestParameters['createdAtFrom'] != null) {
            queryParameters['createdAtFrom'] = requestParameters['createdAtFrom'];
        }

        if (requestParameters['createdAtTo'] != null) {
            queryParameters['createdAtTo'] = requestParameters['createdAtTo'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['dueDateFrom'] != null) {
            queryParameters['dueDateFrom'] = requestParameters['dueDateFrom'];
        }

        if (requestParameters['dueDateTo'] != null) {
            queryParameters['dueDateTo'] = requestParameters['dueDateTo'];
        }

        if (requestParameters['finalAmountFrom'] != null) {
            queryParameters['finalAmountFrom'] = requestParameters['finalAmountFrom'];
        }

        if (requestParameters['finalAmountTo'] != null) {
            queryParameters['finalAmountTo'] = requestParameters['finalAmountTo'];
        }

        if (requestParameters['installmentFinancialRecord'] != null) {
            queryParameters['installmentFinancialRecord'] = requestParameters['installmentFinancialRecord'];
        }

        if (requestParameters['recurringFinancialRecord'] != null) {
            queryParameters['recurringFinancialRecord'] = requestParameters['recurringFinancialRecord'];
        }

        if (requestParameters['reconciled'] != null) {
            queryParameters['reconciled'] = requestParameters['reconciled'];
        }

        if (requestParameters['subcategory'] != null) {
            queryParameters['subcategory'] = requestParameters['subcategory'];
        }

        if (requestParameters['tags'] != null) {
            queryParameters['tags'] = requestParameters['tags'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/external/financial-records/aggregated-result/report`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FinancialRecordsAggregatedResultReportEntityFromJSON(jsonValue));
    }

    /**
     * Get aggregated result report for financial records
     */
    async getAggregatedResultReport(requestParameters: GetAggregatedResultReportRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FinancialRecordsAggregatedResultReportEntity> {
        const response = await this.getAggregatedResultReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get aggregated   result report for financial records
     */
    async systemGetAggregatedResultReportRaw(requestParameters: SystemGetAggregatedResultReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FinancialRecordsAggregatedResultReportEntity>> {
        const queryParameters: any = {};

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        if (requestParameters['amountFrom'] != null) {
            queryParameters['amountFrom'] = requestParameters['amountFrom'];
        }

        if (requestParameters['amountTo'] != null) {
            queryParameters['amountTo'] = requestParameters['amountTo'];
        }

        if (requestParameters['amountType'] != null) {
            queryParameters['amountType'] = requestParameters['amountType'];
        }

        if (requestParameters['cashDateFrom'] != null) {
            queryParameters['cashDateFrom'] = requestParameters['cashDateFrom'];
        }

        if (requestParameters['cashDateTo'] != null) {
            queryParameters['cashDateTo'] = requestParameters['cashDateTo'];
        }

        if (requestParameters['competenceDateFrom'] != null) {
            queryParameters['competenceDateFrom'] = requestParameters['competenceDateFrom'];
        }

        if (requestParameters['competenceDateTo'] != null) {
            queryParameters['competenceDateTo'] = requestParameters['competenceDateTo'];
        }

        if (requestParameters['completed'] != null) {
            queryParameters['completed'] = requestParameters['completed'];
        }

        if (requestParameters['contact'] != null) {
            queryParameters['contact'] = requestParameters['contact'];
        }

        if (requestParameters['createdAtFrom'] != null) {
            queryParameters['createdAtFrom'] = requestParameters['createdAtFrom'];
        }

        if (requestParameters['createdAtTo'] != null) {
            queryParameters['createdAtTo'] = requestParameters['createdAtTo'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['dueDateFrom'] != null) {
            queryParameters['dueDateFrom'] = requestParameters['dueDateFrom'];
        }

        if (requestParameters['dueDateTo'] != null) {
            queryParameters['dueDateTo'] = requestParameters['dueDateTo'];
        }

        if (requestParameters['finalAmountFrom'] != null) {
            queryParameters['finalAmountFrom'] = requestParameters['finalAmountFrom'];
        }

        if (requestParameters['finalAmountTo'] != null) {
            queryParameters['finalAmountTo'] = requestParameters['finalAmountTo'];
        }

        if (requestParameters['installmentFinancialRecord'] != null) {
            queryParameters['installmentFinancialRecord'] = requestParameters['installmentFinancialRecord'];
        }

        if (requestParameters['recurringFinancialRecord'] != null) {
            queryParameters['recurringFinancialRecord'] = requestParameters['recurringFinancialRecord'];
        }

        if (requestParameters['reconciled'] != null) {
            queryParameters['reconciled'] = requestParameters['reconciled'];
        }

        if (requestParameters['subcategory'] != null) {
            queryParameters['subcategory'] = requestParameters['subcategory'];
        }

        if (requestParameters['tags'] != null) {
            queryParameters['tags'] = requestParameters['tags'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/internal/financial-records/aggregated-result/report`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FinancialRecordsAggregatedResultReportEntityFromJSON(jsonValue));
    }

    /**
     * Get aggregated   result report for financial records
     */
    async systemGetAggregatedResultReport(requestParameters: SystemGetAggregatedResultReportRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FinancialRecordsAggregatedResultReportEntity> {
        const response = await this.systemGetAggregatedResultReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GenerateAggregatedFinancialRecordsReportAggregationDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type GenerateAggregatedFinancialRecordsReportAggregationDirectionEnum = typeof GenerateAggregatedFinancialRecordsReportAggregationDirectionEnum[keyof typeof GenerateAggregatedFinancialRecordsReportAggregationDirectionEnum];
/**
 * @export
 */
export const GenerateAggregatedFinancialRecordsReportGroupByEnum = {
    Category: 'category',
    Contact: 'contact',
    Tag: 'tag'
} as const;
export type GenerateAggregatedFinancialRecordsReportGroupByEnum = typeof GenerateAggregatedFinancialRecordsReportGroupByEnum[keyof typeof GenerateAggregatedFinancialRecordsReportGroupByEnum];
/**
 * @export
 */
export const GenerateAggregatedFinancialRecordsReportAmountTypeEnum = {
    Base: 'base',
    Final: 'final'
} as const;
export type GenerateAggregatedFinancialRecordsReportAmountTypeEnum = typeof GenerateAggregatedFinancialRecordsReportAmountTypeEnum[keyof typeof GenerateAggregatedFinancialRecordsReportAmountTypeEnum];
/**
 * @export
 */
export const GenerateAggregatedFinancialRecordsReportDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type GenerateAggregatedFinancialRecordsReportDirectionEnum = typeof GenerateAggregatedFinancialRecordsReportDirectionEnum[keyof typeof GenerateAggregatedFinancialRecordsReportDirectionEnum];
/**
 * @export
 */
export const GenerateAggregatedFinancialRecordsReportSortOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type GenerateAggregatedFinancialRecordsReportSortOrderEnum = typeof GenerateAggregatedFinancialRecordsReportSortOrderEnum[keyof typeof GenerateAggregatedFinancialRecordsReportSortOrderEnum];
/**
 * @export
 */
export const GenerateMonthlyFinancialReportAmountTypeEnum = {
    Base: 'base',
    Final: 'final'
} as const;
export type GenerateMonthlyFinancialReportAmountTypeEnum = typeof GenerateMonthlyFinancialReportAmountTypeEnum[keyof typeof GenerateMonthlyFinancialReportAmountTypeEnum];
/**
 * @export
 */
export const GenerateMonthlyFinancialReportDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type GenerateMonthlyFinancialReportDirectionEnum = typeof GenerateMonthlyFinancialReportDirectionEnum[keyof typeof GenerateMonthlyFinancialReportDirectionEnum];
/**
 * @export
 */
export const GetAggregatedResultReportAmountTypeEnum = {
    Base: 'base',
    Final: 'final'
} as const;
export type GetAggregatedResultReportAmountTypeEnum = typeof GetAggregatedResultReportAmountTypeEnum[keyof typeof GetAggregatedResultReportAmountTypeEnum];
/**
 * @export
 */
export const GetAggregatedResultReportDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type GetAggregatedResultReportDirectionEnum = typeof GetAggregatedResultReportDirectionEnum[keyof typeof GetAggregatedResultReportDirectionEnum];
/**
 * @export
 */
export const SystemGetAggregatedResultReportAmountTypeEnum = {
    Base: 'base',
    Final: 'final'
} as const;
export type SystemGetAggregatedResultReportAmountTypeEnum = typeof SystemGetAggregatedResultReportAmountTypeEnum[keyof typeof SystemGetAggregatedResultReportAmountTypeEnum];
/**
 * @export
 */
export const SystemGetAggregatedResultReportDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type SystemGetAggregatedResultReportDirectionEnum = typeof SystemGetAggregatedResultReportDirectionEnum[keyof typeof SystemGetAggregatedResultReportDirectionEnum];
