/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AggregatedFinancialRecordsReportEntityDataDataInner
 */
export interface AggregatedFinancialRecordsReportEntityDataDataInner {
    /**
     * Rótulo do item agrupado
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataDataInner
     */
    label: string;
    /**
     * Valor total do item agrupado em centavos, em formato string
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataDataInner
     */
    totalAmount: string;
}

/**
 * Check if a given object implements the AggregatedFinancialRecordsReportEntityDataDataInner interface.
 */
export function instanceOfAggregatedFinancialRecordsReportEntityDataDataInner(value: object): value is AggregatedFinancialRecordsReportEntityDataDataInner {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('totalAmount' in value) || value['totalAmount'] === undefined) return false;
    return true;
}

export function AggregatedFinancialRecordsReportEntityDataDataInnerFromJSON(json: any): AggregatedFinancialRecordsReportEntityDataDataInner {
    return AggregatedFinancialRecordsReportEntityDataDataInnerFromJSONTyped(json, false);
}

export function AggregatedFinancialRecordsReportEntityDataDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregatedFinancialRecordsReportEntityDataDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'totalAmount': json['totalAmount'],
    };
}

export function AggregatedFinancialRecordsReportEntityDataDataInnerToJSON(json: any): AggregatedFinancialRecordsReportEntityDataDataInner {
    return AggregatedFinancialRecordsReportEntityDataDataInnerToJSONTyped(json, false);
}

export function AggregatedFinancialRecordsReportEntityDataDataInnerToJSONTyped(value?: AggregatedFinancialRecordsReportEntityDataDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'totalAmount': value['totalAmount'],
    };
}

