/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AggregatedFinancialRecordsReportEntityDataFilters } from './AggregatedFinancialRecordsReportEntityDataFilters';
import {
    AggregatedFinancialRecordsReportEntityDataFiltersFromJSON,
    AggregatedFinancialRecordsReportEntityDataFiltersFromJSONTyped,
    AggregatedFinancialRecordsReportEntityDataFiltersToJSON,
    AggregatedFinancialRecordsReportEntityDataFiltersToJSONTyped,
} from './AggregatedFinancialRecordsReportEntityDataFilters';
import type { AggregatedFinancialRecordsReportEntityDataDataInner } from './AggregatedFinancialRecordsReportEntityDataDataInner';
import {
    AggregatedFinancialRecordsReportEntityDataDataInnerFromJSON,
    AggregatedFinancialRecordsReportEntityDataDataInnerFromJSONTyped,
    AggregatedFinancialRecordsReportEntityDataDataInnerToJSON,
    AggregatedFinancialRecordsReportEntityDataDataInnerToJSONTyped,
} from './AggregatedFinancialRecordsReportEntityDataDataInner';

/**
 * 
 * @export
 * @interface AggregatedFinancialRecordsReportEntityData
 */
export interface AggregatedFinancialRecordsReportEntityData {
    /**
     * 
     * @type {AggregatedFinancialRecordsReportEntityDataFilters}
     * @memberof AggregatedFinancialRecordsReportEntityData
     */
    filters: AggregatedFinancialRecordsReportEntityDataFilters;
    /**
     * Dados agregados
     * @type {Array<AggregatedFinancialRecordsReportEntityDataDataInner>}
     * @memberof AggregatedFinancialRecordsReportEntityData
     */
    data: Array<AggregatedFinancialRecordsReportEntityDataDataInner>;
}

/**
 * Check if a given object implements the AggregatedFinancialRecordsReportEntityData interface.
 */
export function instanceOfAggregatedFinancialRecordsReportEntityData(value: object): value is AggregatedFinancialRecordsReportEntityData {
    if (!('filters' in value) || value['filters'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AggregatedFinancialRecordsReportEntityDataFromJSON(json: any): AggregatedFinancialRecordsReportEntityData {
    return AggregatedFinancialRecordsReportEntityDataFromJSONTyped(json, false);
}

export function AggregatedFinancialRecordsReportEntityDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregatedFinancialRecordsReportEntityData {
    if (json == null) {
        return json;
    }
    return {
        
        'filters': AggregatedFinancialRecordsReportEntityDataFiltersFromJSON(json['filters']),
        'data': ((json['data'] as Array<any>).map(AggregatedFinancialRecordsReportEntityDataDataInnerFromJSON)),
    };
}

export function AggregatedFinancialRecordsReportEntityDataToJSON(json: any): AggregatedFinancialRecordsReportEntityData {
    return AggregatedFinancialRecordsReportEntityDataToJSONTyped(json, false);
}

export function AggregatedFinancialRecordsReportEntityDataToJSONTyped(value?: AggregatedFinancialRecordsReportEntityData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filters': AggregatedFinancialRecordsReportEntityDataFiltersToJSON(value['filters']),
        'data': ((value['data'] as Array<any>).map(AggregatedFinancialRecordsReportEntityDataDataInnerToJSON)),
    };
}

