/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Filtros aplicados
 * @export
 * @interface AggregatedFinancialRecordsReportEntityDataFilters
 */
export interface AggregatedFinancialRecordsReportEntityDataFilters {
    /**
     * 
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    direction?: AggregatedFinancialRecordsReportEntityDataFiltersDirectionEnum;
    /**
     * 
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    dueDateFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    dueDateTo?: string;
    /**
     * 
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    contact?: string;
    /**
     * 
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    subcategory?: string;
    /**
     * 
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    competenceDateFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    competenceDateTo?: string;
    /**
     * 
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    cashDateFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    cashDateTo?: string;
    /**
     * 
     * @type {any}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    createdAtFrom?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    createdAtTo?: any | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    tags?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    completed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    reconciled?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    account?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    installmentFinancialRecord?: string;
    /**
     * 
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    recurringFinancialRecord?: string;
    /**
     * 
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    amountType?: AggregatedFinancialRecordsReportEntityDataFiltersAmountTypeEnum;
    /**
     * Campo para agrupamento dos dados
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    groupBy: AggregatedFinancialRecordsReportEntityDataFiltersGroupByEnum;
    /**
     * Ordem de classificação
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    sortOrder?: AggregatedFinancialRecordsReportEntityDataFiltersSortOrderEnum;
    /**
     * Direção do lançamento financeiro
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntityDataFilters
     */
    aggregationDirection: AggregatedFinancialRecordsReportEntityDataFiltersAggregationDirectionEnum;
}


/**
 * @export
 */
export const AggregatedFinancialRecordsReportEntityDataFiltersDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type AggregatedFinancialRecordsReportEntityDataFiltersDirectionEnum = typeof AggregatedFinancialRecordsReportEntityDataFiltersDirectionEnum[keyof typeof AggregatedFinancialRecordsReportEntityDataFiltersDirectionEnum];

/**
 * @export
 */
export const AggregatedFinancialRecordsReportEntityDataFiltersAmountTypeEnum = {
    Base: 'base',
    Final: 'final'
} as const;
export type AggregatedFinancialRecordsReportEntityDataFiltersAmountTypeEnum = typeof AggregatedFinancialRecordsReportEntityDataFiltersAmountTypeEnum[keyof typeof AggregatedFinancialRecordsReportEntityDataFiltersAmountTypeEnum];

/**
 * @export
 */
export const AggregatedFinancialRecordsReportEntityDataFiltersGroupByEnum = {
    Category: 'category',
    Contact: 'contact',
    Tag: 'tag'
} as const;
export type AggregatedFinancialRecordsReportEntityDataFiltersGroupByEnum = typeof AggregatedFinancialRecordsReportEntityDataFiltersGroupByEnum[keyof typeof AggregatedFinancialRecordsReportEntityDataFiltersGroupByEnum];

/**
 * @export
 */
export const AggregatedFinancialRecordsReportEntityDataFiltersSortOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type AggregatedFinancialRecordsReportEntityDataFiltersSortOrderEnum = typeof AggregatedFinancialRecordsReportEntityDataFiltersSortOrderEnum[keyof typeof AggregatedFinancialRecordsReportEntityDataFiltersSortOrderEnum];

/**
 * @export
 */
export const AggregatedFinancialRecordsReportEntityDataFiltersAggregationDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type AggregatedFinancialRecordsReportEntityDataFiltersAggregationDirectionEnum = typeof AggregatedFinancialRecordsReportEntityDataFiltersAggregationDirectionEnum[keyof typeof AggregatedFinancialRecordsReportEntityDataFiltersAggregationDirectionEnum];


/**
 * Check if a given object implements the AggregatedFinancialRecordsReportEntityDataFilters interface.
 */
export function instanceOfAggregatedFinancialRecordsReportEntityDataFilters(value: object): value is AggregatedFinancialRecordsReportEntityDataFilters {
    if (!('groupBy' in value) || value['groupBy'] === undefined) return false;
    if (!('aggregationDirection' in value) || value['aggregationDirection'] === undefined) return false;
    return true;
}

export function AggregatedFinancialRecordsReportEntityDataFiltersFromJSON(json: any): AggregatedFinancialRecordsReportEntityDataFilters {
    return AggregatedFinancialRecordsReportEntityDataFiltersFromJSONTyped(json, false);
}

export function AggregatedFinancialRecordsReportEntityDataFiltersFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregatedFinancialRecordsReportEntityDataFilters {
    if (json == null) {
        return json;
    }
    return {
        
        'direction': json['direction'] == null ? undefined : json['direction'],
        'dueDateFrom': json['dueDateFrom'] == null ? undefined : json['dueDateFrom'],
        'dueDateTo': json['dueDateTo'] == null ? undefined : json['dueDateTo'],
        'contact': json['contact'] == null ? undefined : json['contact'],
        'subcategory': json['subcategory'] == null ? undefined : json['subcategory'],
        'competenceDateFrom': json['competenceDateFrom'] == null ? undefined : json['competenceDateFrom'],
        'competenceDateTo': json['competenceDateTo'] == null ? undefined : json['competenceDateTo'],
        'cashDateFrom': json['cashDateFrom'] == null ? undefined : json['cashDateFrom'],
        'cashDateTo': json['cashDateTo'] == null ? undefined : json['cashDateTo'],
        'createdAtFrom': json['createdAtFrom'] == null ? undefined : json['createdAtFrom'],
        'createdAtTo': json['createdAtTo'] == null ? undefined : json['createdAtTo'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'completed': json['completed'] == null ? undefined : json['completed'],
        'reconciled': json['reconciled'] == null ? undefined : json['reconciled'],
        'account': json['account'] == null ? undefined : json['account'],
        'installmentFinancialRecord': json['installmentFinancialRecord'] == null ? undefined : json['installmentFinancialRecord'],
        'recurringFinancialRecord': json['recurringFinancialRecord'] == null ? undefined : json['recurringFinancialRecord'],
        'amountType': json['amountType'] == null ? undefined : json['amountType'],
        'groupBy': json['groupBy'],
        'sortOrder': json['sortOrder'] == null ? undefined : json['sortOrder'],
        'aggregationDirection': json['aggregationDirection'],
    };
}

export function AggregatedFinancialRecordsReportEntityDataFiltersToJSON(json: any): AggregatedFinancialRecordsReportEntityDataFilters {
    return AggregatedFinancialRecordsReportEntityDataFiltersToJSONTyped(json, false);
}

export function AggregatedFinancialRecordsReportEntityDataFiltersToJSONTyped(value?: AggregatedFinancialRecordsReportEntityDataFilters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'direction': value['direction'],
        'dueDateFrom': value['dueDateFrom'],
        'dueDateTo': value['dueDateTo'],
        'contact': value['contact'],
        'subcategory': value['subcategory'],
        'competenceDateFrom': value['competenceDateFrom'],
        'competenceDateTo': value['competenceDateTo'],
        'cashDateFrom': value['cashDateFrom'],
        'cashDateTo': value['cashDateTo'],
        'createdAtFrom': value['createdAtFrom'],
        'createdAtTo': value['createdAtTo'],
        'tags': value['tags'],
        'completed': value['completed'],
        'reconciled': value['reconciled'],
        'account': value['account'],
        'installmentFinancialRecord': value['installmentFinancialRecord'],
        'recurringFinancialRecord': value['recurringFinancialRecord'],
        'amountType': value['amountType'],
        'groupBy': value['groupBy'],
        'sortOrder': value['sortOrder'],
        'aggregationDirection': value['aggregationDirection'],
    };
}

