/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AggregatedFinancialRecordsReportEntityData } from './AggregatedFinancialRecordsReportEntityData';
import {
    AggregatedFinancialRecordsReportEntityDataFromJSON,
    AggregatedFinancialRecordsReportEntityDataFromJSONTyped,
    AggregatedFinancialRecordsReportEntityDataToJSON,
    AggregatedFinancialRecordsReportEntityDataToJSONTyped,
} from './AggregatedFinancialRecordsReportEntityData';

/**
 * 
 * @export
 * @interface AggregatedFinancialRecordsReportEntity
 */
export interface AggregatedFinancialRecordsReportEntity {
    /**
     * 
     * @type {string}
     * @memberof AggregatedFinancialRecordsReportEntity
     */
    type: AggregatedFinancialRecordsReportEntityTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof AggregatedFinancialRecordsReportEntity
     */
    generatedAt: any | null;
    /**
     * 
     * @type {AggregatedFinancialRecordsReportEntityData}
     * @memberof AggregatedFinancialRecordsReportEntity
     */
    data: AggregatedFinancialRecordsReportEntityData;
}


/**
 * @export
 */
export const AggregatedFinancialRecordsReportEntityTypeEnum = {
    AggregatedFinancialRecordsReport: 'AGGREGATED_FINANCIAL_RECORDS_REPORT'
} as const;
export type AggregatedFinancialRecordsReportEntityTypeEnum = typeof AggregatedFinancialRecordsReportEntityTypeEnum[keyof typeof AggregatedFinancialRecordsReportEntityTypeEnum];


/**
 * Check if a given object implements the AggregatedFinancialRecordsReportEntity interface.
 */
export function instanceOfAggregatedFinancialRecordsReportEntity(value: object): value is AggregatedFinancialRecordsReportEntity {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AggregatedFinancialRecordsReportEntityFromJSON(json: any): AggregatedFinancialRecordsReportEntity {
    return AggregatedFinancialRecordsReportEntityFromJSONTyped(json, false);
}

export function AggregatedFinancialRecordsReportEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregatedFinancialRecordsReportEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'generatedAt': json['generatedAt'],
        'data': AggregatedFinancialRecordsReportEntityDataFromJSON(json['data']),
    };
}

export function AggregatedFinancialRecordsReportEntityToJSON(json: any): AggregatedFinancialRecordsReportEntity {
    return AggregatedFinancialRecordsReportEntityToJSONTyped(json, false);
}

export function AggregatedFinancialRecordsReportEntityToJSONTyped(value?: AggregatedFinancialRecordsReportEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'generatedAt': value['generatedAt'],
        'data': AggregatedFinancialRecordsReportEntityDataToJSON(value['data']),
    };
}

