/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BankAccountsDashboardReportEntityDataBankAccountsInner } from './BankAccountsDashboardReportEntityDataBankAccountsInner';
import {
    BankAccountsDashboardReportEntityDataBankAccountsInnerFromJSON,
    BankAccountsDashboardReportEntityDataBankAccountsInnerFromJSONTyped,
    BankAccountsDashboardReportEntityDataBankAccountsInnerToJSON,
    BankAccountsDashboardReportEntityDataBankAccountsInnerToJSONTyped,
} from './BankAccountsDashboardReportEntityDataBankAccountsInner';

/**
 * 
 * @export
 * @interface BankAccountsDashboardReportEntityData
 */
export interface BankAccountsDashboardReportEntityData {
    /**
     * 
     * @type {Array<BankAccountsDashboardReportEntityDataBankAccountsInner>}
     * @memberof BankAccountsDashboardReportEntityData
     */
    bankAccounts: Array<BankAccountsDashboardReportEntityDataBankAccountsInner>;
}

/**
 * Check if a given object implements the BankAccountsDashboardReportEntityData interface.
 */
export function instanceOfBankAccountsDashboardReportEntityData(value: object): value is BankAccountsDashboardReportEntityData {
    if (!('bankAccounts' in value) || value['bankAccounts'] === undefined) return false;
    return true;
}

export function BankAccountsDashboardReportEntityDataFromJSON(json: any): BankAccountsDashboardReportEntityData {
    return BankAccountsDashboardReportEntityDataFromJSONTyped(json, false);
}

export function BankAccountsDashboardReportEntityDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAccountsDashboardReportEntityData {
    if (json == null) {
        return json;
    }
    return {
        
        'bankAccounts': ((json['bankAccounts'] as Array<any>).map(BankAccountsDashboardReportEntityDataBankAccountsInnerFromJSON)),
    };
}

export function BankAccountsDashboardReportEntityDataToJSON(json: any): BankAccountsDashboardReportEntityData {
    return BankAccountsDashboardReportEntityDataToJSONTyped(json, false);
}

export function BankAccountsDashboardReportEntityDataToJSONTyped(value?: BankAccountsDashboardReportEntityData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bankAccounts': ((value['bankAccounts'] as Array<any>).map(BankAccountsDashboardReportEntityDataBankAccountsInnerToJSON)),
    };
}

