/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BankAccountsDashboardReportEntityData } from './BankAccountsDashboardReportEntityData';
import {
    BankAccountsDashboardReportEntityDataFromJSON,
    BankAccountsDashboardReportEntityDataFromJSONTyped,
    BankAccountsDashboardReportEntityDataToJSON,
    BankAccountsDashboardReportEntityDataToJSONTyped,
} from './BankAccountsDashboardReportEntityData';

/**
 * 
 * @export
 * @interface BankAccountsDashboardReportEntity
 */
export interface BankAccountsDashboardReportEntity {
    /**
     * 
     * @type {string}
     * @memberof BankAccountsDashboardReportEntity
     */
    type: BankAccountsDashboardReportEntityTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof BankAccountsDashboardReportEntity
     */
    generatedAt: any | null;
    /**
     * 
     * @type {BankAccountsDashboardReportEntityData}
     * @memberof BankAccountsDashboardReportEntity
     */
    data: BankAccountsDashboardReportEntityData;
}


/**
 * @export
 */
export const BankAccountsDashboardReportEntityTypeEnum = {
    FinancialRecordsAggregateResultReport: 'FINANCIAL_RECORDS_AGGREGATE_RESULT_REPORT',
    FinancialRecordsByContactsReport: 'FINANCIAL_RECORDS_BY_CONTACTS_REPORT',
    BankAccountsCurrentBalanceReport: 'BANK_ACCOUNTS_CURRENT_BALANCE_REPORT',
    CashFlowReport: 'CASH_FLOW_REPORT',
    FinancialStatementReport: 'FINANCIAL_STATEMENT_REPORT',
    AggregatedFinancialRecordsReport: 'AGGREGATED_FINANCIAL_RECORDS_REPORT',
    MonthlyFinancialReport: 'MONTHLY_FINANCIAL_REPORT',
    FinancialMeasuresReport: 'FINANCIAL_MEASURES_REPORT',
    FinancialResultCompositionReport: 'FINANCIAL_RESULT_COMPOSITION_REPORT',
    BankAccountsDashboardReport: 'BANK_ACCOUNTS_DASHBOARD_REPORT'
} as const;
export type BankAccountsDashboardReportEntityTypeEnum = typeof BankAccountsDashboardReportEntityTypeEnum[keyof typeof BankAccountsDashboardReportEntityTypeEnum];


/**
 * Check if a given object implements the BankAccountsDashboardReportEntity interface.
 */
export function instanceOfBankAccountsDashboardReportEntity(value: object): value is BankAccountsDashboardReportEntity {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function BankAccountsDashboardReportEntityFromJSON(json: any): BankAccountsDashboardReportEntity {
    return BankAccountsDashboardReportEntityFromJSONTyped(json, false);
}

export function BankAccountsDashboardReportEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAccountsDashboardReportEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'generatedAt': json['generatedAt'],
        'data': BankAccountsDashboardReportEntityDataFromJSON(json['data']),
    };
}

export function BankAccountsDashboardReportEntityToJSON(json: any): BankAccountsDashboardReportEntity {
    return BankAccountsDashboardReportEntityToJSONTyped(json, false);
}

export function BankAccountsDashboardReportEntityToJSONTyped(value?: BankAccountsDashboardReportEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'generatedAt': value['generatedAt'],
        'data': BankAccountsDashboardReportEntityDataToJSON(value['data']),
    };
}

