/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashFlowReportEntityDataDataInner } from './CashFlowReportEntityDataDataInner';
import {
    CashFlowReportEntityDataDataInnerFromJSON,
    CashFlowReportEntityDataDataInnerFromJSONTyped,
    CashFlowReportEntityDataDataInnerToJSON,
    CashFlowReportEntityDataDataInnerToJSONTyped,
} from './CashFlowReportEntityDataDataInner';
import type { CashFlowReportEntityDataFilters } from './CashFlowReportEntityDataFilters';
import {
    CashFlowReportEntityDataFiltersFromJSON,
    CashFlowReportEntityDataFiltersFromJSONTyped,
    CashFlowReportEntityDataFiltersToJSON,
    CashFlowReportEntityDataFiltersToJSONTyped,
} from './CashFlowReportEntityDataFilters';
import type { CashFlowReportEntityDataSummary } from './CashFlowReportEntityDataSummary';
import {
    CashFlowReportEntityDataSummaryFromJSON,
    CashFlowReportEntityDataSummaryFromJSONTyped,
    CashFlowReportEntityDataSummaryToJSON,
    CashFlowReportEntityDataSummaryToJSONTyped,
} from './CashFlowReportEntityDataSummary';

/**
 * 
 * @export
 * @interface CashFlowReportEntityData
 */
export interface CashFlowReportEntityData {
    /**
     * 
     * @type {CashFlowReportEntityDataFilters}
     * @memberof CashFlowReportEntityData
     */
    filters: CashFlowReportEntityDataFilters;
    /**
     * 
     * @type {Array<CashFlowReportEntityDataDataInner>}
     * @memberof CashFlowReportEntityData
     */
    data: Array<CashFlowReportEntityDataDataInner>;
    /**
     * 
     * @type {CashFlowReportEntityDataSummary}
     * @memberof CashFlowReportEntityData
     */
    summary: CashFlowReportEntityDataSummary;
}

/**
 * Check if a given object implements the CashFlowReportEntityData interface.
 */
export function instanceOfCashFlowReportEntityData(value: object): value is CashFlowReportEntityData {
    if (!('filters' in value) || value['filters'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function CashFlowReportEntityDataFromJSON(json: any): CashFlowReportEntityData {
    return CashFlowReportEntityDataFromJSONTyped(json, false);
}

export function CashFlowReportEntityDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashFlowReportEntityData {
    if (json == null) {
        return json;
    }
    return {
        
        'filters': CashFlowReportEntityDataFiltersFromJSON(json['filters']),
        'data': ((json['data'] as Array<any>).map(CashFlowReportEntityDataDataInnerFromJSON)),
        'summary': CashFlowReportEntityDataSummaryFromJSON(json['summary']),
    };
}

export function CashFlowReportEntityDataToJSON(json: any): CashFlowReportEntityData {
    return CashFlowReportEntityDataToJSONTyped(json, false);
}

export function CashFlowReportEntityDataToJSONTyped(value?: CashFlowReportEntityData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filters': CashFlowReportEntityDataFiltersToJSON(value['filters']),
        'data': ((value['data'] as Array<any>).map(CashFlowReportEntityDataDataInnerToJSON)),
        'summary': CashFlowReportEntityDataSummaryToJSON(value['summary']),
    };
}

