/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashFlowReportEntityDataDataInnerPeriod } from './CashFlowReportEntityDataDataInnerPeriod';
import {
    CashFlowReportEntityDataDataInnerPeriodFromJSON,
    CashFlowReportEntityDataDataInnerPeriodFromJSONTyped,
    CashFlowReportEntityDataDataInnerPeriodToJSON,
    CashFlowReportEntityDataDataInnerPeriodToJSONTyped,
} from './CashFlowReportEntityDataDataInnerPeriod';

/**
 * 
 * @export
 * @interface CashFlowReportEntityDataDataInner
 */
export interface CashFlowReportEntityDataDataInner {
    /**
     * 
     * @type {CashFlowReportEntityDataDataInnerPeriod}
     * @memberof CashFlowReportEntityDataDataInner
     */
    period: CashFlowReportEntityDataDataInnerPeriod;
    /**
     * Saldo no início do período
     * @type {number}
     * @memberof CashFlowReportEntityDataDataInner
     */
    openingBalance: number;
    /**
     * Soma das transações de ENTRADA no período
     * @type {number}
     * @memberof CashFlowReportEntityDataDataInner
     */
    totalIncome: number;
    /**
     * Soma das transações de SAÍDA no período
     * @type {number}
     * @memberof CashFlowReportEntityDataDataInner
     */
    totalOutcome: number;
    /**
     * Saldo no fim do período
     * @type {number}
     * @memberof CashFlowReportEntityDataDataInner
     */
    closingBalance: number;
}

/**
 * Check if a given object implements the CashFlowReportEntityDataDataInner interface.
 */
export function instanceOfCashFlowReportEntityDataDataInner(value: object): value is CashFlowReportEntityDataDataInner {
    if (!('period' in value) || value['period'] === undefined) return false;
    if (!('openingBalance' in value) || value['openingBalance'] === undefined) return false;
    if (!('totalIncome' in value) || value['totalIncome'] === undefined) return false;
    if (!('totalOutcome' in value) || value['totalOutcome'] === undefined) return false;
    if (!('closingBalance' in value) || value['closingBalance'] === undefined) return false;
    return true;
}

export function CashFlowReportEntityDataDataInnerFromJSON(json: any): CashFlowReportEntityDataDataInner {
    return CashFlowReportEntityDataDataInnerFromJSONTyped(json, false);
}

export function CashFlowReportEntityDataDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashFlowReportEntityDataDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'period': CashFlowReportEntityDataDataInnerPeriodFromJSON(json['period']),
        'openingBalance': json['openingBalance'],
        'totalIncome': json['totalIncome'],
        'totalOutcome': json['totalOutcome'],
        'closingBalance': json['closingBalance'],
    };
}

export function CashFlowReportEntityDataDataInnerToJSON(json: any): CashFlowReportEntityDataDataInner {
    return CashFlowReportEntityDataDataInnerToJSONTyped(json, false);
}

export function CashFlowReportEntityDataDataInnerToJSONTyped(value?: CashFlowReportEntityDataDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'period': CashFlowReportEntityDataDataInnerPeriodToJSON(value['period']),
        'openingBalance': value['openingBalance'],
        'totalIncome': value['totalIncome'],
        'totalOutcome': value['totalOutcome'],
        'closingBalance': value['closingBalance'],
    };
}

