/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Período
 * @export
 * @interface CashFlowReportEntityDataDataInnerPeriod
 */
export interface CashFlowReportEntityDataDataInnerPeriod {
    /**
     * Data de início do período
     * @type {string}
     * @memberof CashFlowReportEntityDataDataInnerPeriod
     */
    start: string;
    /**
     * Data de fim do período
     * @type {string}
     * @memberof CashFlowReportEntityDataDataInnerPeriod
     */
    end: string;
    /**
     * Nome do período
     * @type {string}
     * @memberof CashFlowReportEntityDataDataInnerPeriod
     */
    name: string;
}

/**
 * Check if a given object implements the CashFlowReportEntityDataDataInnerPeriod interface.
 */
export function instanceOfCashFlowReportEntityDataDataInnerPeriod(value: object): value is CashFlowReportEntityDataDataInnerPeriod {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CashFlowReportEntityDataDataInnerPeriodFromJSON(json: any): CashFlowReportEntityDataDataInnerPeriod {
    return CashFlowReportEntityDataDataInnerPeriodFromJSONTyped(json, false);
}

export function CashFlowReportEntityDataDataInnerPeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashFlowReportEntityDataDataInnerPeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'],
        'end': json['end'],
        'name': json['name'],
    };
}

export function CashFlowReportEntityDataDataInnerPeriodToJSON(json: any): CashFlowReportEntityDataDataInnerPeriod {
    return CashFlowReportEntityDataDataInnerPeriodToJSONTyped(json, false);
}

export function CashFlowReportEntityDataDataInnerPeriodToJSONTyped(value?: CashFlowReportEntityDataDataInnerPeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'],
        'end': value['end'],
        'name': value['name'],
    };
}

