/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashFlowReportEntityData } from './CashFlowReportEntityData';
import {
    CashFlowReportEntityDataFromJSON,
    CashFlowReportEntityDataFromJSONTyped,
    CashFlowReportEntityDataToJSON,
    CashFlowReportEntityDataToJSONTyped,
} from './CashFlowReportEntityData';

/**
 * 
 * @export
 * @interface CashFlowReportEntity
 */
export interface CashFlowReportEntity {
    /**
     * 
     * @type {string}
     * @memberof CashFlowReportEntity
     */
    type: CashFlowReportEntityTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof CashFlowReportEntity
     */
    generatedAt: any | null;
    /**
     * 
     * @type {CashFlowReportEntityData}
     * @memberof CashFlowReportEntity
     */
    data: CashFlowReportEntityData;
}


/**
 * @export
 */
export const CashFlowReportEntityTypeEnum = {
    CashFlowReport: 'CASH_FLOW_REPORT'
} as const;
export type CashFlowReportEntityTypeEnum = typeof CashFlowReportEntityTypeEnum[keyof typeof CashFlowReportEntityTypeEnum];


/**
 * Check if a given object implements the CashFlowReportEntity interface.
 */
export function instanceOfCashFlowReportEntity(value: object): value is CashFlowReportEntity {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CashFlowReportEntityFromJSON(json: any): CashFlowReportEntity {
    return CashFlowReportEntityFromJSONTyped(json, false);
}

export function CashFlowReportEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashFlowReportEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'generatedAt': json['generatedAt'],
        'data': CashFlowReportEntityDataFromJSON(json['data']),
    };
}

export function CashFlowReportEntityToJSON(json: any): CashFlowReportEntity {
    return CashFlowReportEntityToJSONTyped(json, false);
}

export function CashFlowReportEntityToJSONTyped(value?: CashFlowReportEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'generatedAt': value['generatedAt'],
        'data': CashFlowReportEntityDataToJSON(value['data']),
    };
}

