/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CashFlowReportEntityDataDataInnerInsertedAccountsInner
 */
export interface CashFlowReportEntityDataDataInnerInsertedAccountsInner {
    /**
     * 
     * @type {string}
     * @memberof CashFlowReportEntityDataDataInnerInsertedAccountsInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CashFlowReportEntityDataDataInnerInsertedAccountsInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CashFlowReportEntityDataDataInnerInsertedAccountsInner
     */
    type: string;
    /**
     * 
     * @type {boolean}
     * @memberof CashFlowReportEntityDataDataInnerInsertedAccountsInner
     */
    active: boolean;
    /**
     * 
     * @type {number}
     * @memberof CashFlowReportEntityDataDataInnerInsertedAccountsInner
     */
    initialBalanceAmount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CashFlowReportEntityDataDataInnerInsertedAccountsInner
     */
    initialBalanceDate?: string | null;
}

/**
 * Check if a given object implements the CashFlowReportEntityDataDataInnerInsertedAccountsInner interface.
 */
export function instanceOfCashFlowReportEntityDataDataInnerInsertedAccountsInner(value: object): value is CashFlowReportEntityDataDataInnerInsertedAccountsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    return true;
}

export function CashFlowReportEntityDataDataInnerInsertedAccountsInnerFromJSON(json: any): CashFlowReportEntityDataDataInnerInsertedAccountsInner {
    return CashFlowReportEntityDataDataInnerInsertedAccountsInnerFromJSONTyped(json, false);
}

export function CashFlowReportEntityDataDataInnerInsertedAccountsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashFlowReportEntityDataDataInnerInsertedAccountsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': json['type'],
        'active': json['active'],
        'initialBalanceAmount': json['initialBalanceAmount'] == null ? undefined : json['initialBalanceAmount'],
        'initialBalanceDate': json['initialBalanceDate'] == null ? undefined : json['initialBalanceDate'],
    };
}

export function CashFlowReportEntityDataDataInnerInsertedAccountsInnerToJSON(json: any): CashFlowReportEntityDataDataInnerInsertedAccountsInner {
    return CashFlowReportEntityDataDataInnerInsertedAccountsInnerToJSONTyped(json, false);
}

export function CashFlowReportEntityDataDataInnerInsertedAccountsInnerToJSONTyped(value?: CashFlowReportEntityDataDataInnerInsertedAccountsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'active': value['active'],
        'initialBalanceAmount': value['initialBalanceAmount'],
        'initialBalanceDate': value['initialBalanceDate'],
    };
}

