/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentMonthCashFlowEntity
 */
export interface CurrentMonthCashFlowEntity {
    /**
     * Valor total de lançamentos concluídos no mês atual
     * @type {number}
     * @memberof CurrentMonthCashFlowEntity
     */
    totalCompletedAmount: number;
    /**
     * Valor total de lançamentos em aberto no mês atual
     * @type {number}
     * @memberof CurrentMonthCashFlowEntity
     */
    totalOpenAmount: number;
}

/**
 * Check if a given object implements the CurrentMonthCashFlowEntity interface.
 */
export function instanceOfCurrentMonthCashFlowEntity(value: object): value is CurrentMonthCashFlowEntity {
    if (!('totalCompletedAmount' in value) || value['totalCompletedAmount'] === undefined) return false;
    if (!('totalOpenAmount' in value) || value['totalOpenAmount'] === undefined) return false;
    return true;
}

export function CurrentMonthCashFlowEntityFromJSON(json: any): CurrentMonthCashFlowEntity {
    return CurrentMonthCashFlowEntityFromJSONTyped(json, false);
}

export function CurrentMonthCashFlowEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentMonthCashFlowEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCompletedAmount': json['totalCompletedAmount'],
        'totalOpenAmount': json['totalOpenAmount'],
    };
}

export function CurrentMonthCashFlowEntityToJSON(json: any): CurrentMonthCashFlowEntity {
    return CurrentMonthCashFlowEntityToJSONTyped(json, false);
}

export function CurrentMonthCashFlowEntityToJSONTyped(value?: CurrentMonthCashFlowEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalCompletedAmount': value['totalCompletedAmount'],
        'totalOpenAmount': value['totalOpenAmount'],
    };
}

