/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialResultCompositionReportEntityData } from './FinancialResultCompositionReportEntityData';
import {
    FinancialResultCompositionReportEntityDataFromJSON,
    FinancialResultCompositionReportEntityDataFromJSONTyped,
    FinancialResultCompositionReportEntityDataToJSON,
    FinancialResultCompositionReportEntityDataToJSONTyped,
} from './FinancialResultCompositionReportEntityData';

/**
 * 
 * @export
 * @interface FinancialResultCompositionReportEntity
 */
export interface FinancialResultCompositionReportEntity {
    /**
     * 
     * @type {string}
     * @memberof FinancialResultCompositionReportEntity
     */
    type: FinancialResultCompositionReportEntityTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof FinancialResultCompositionReportEntity
     */
    generatedAt: any | null;
    /**
     * 
     * @type {FinancialResultCompositionReportEntityData}
     * @memberof FinancialResultCompositionReportEntity
     */
    data: FinancialResultCompositionReportEntityData;
}


/**
 * @export
 */
export const FinancialResultCompositionReportEntityTypeEnum = {
    FinancialResultCompositionReport: 'FINANCIAL_RESULT_COMPOSITION_REPORT'
} as const;
export type FinancialResultCompositionReportEntityTypeEnum = typeof FinancialResultCompositionReportEntityTypeEnum[keyof typeof FinancialResultCompositionReportEntityTypeEnum];


/**
 * Check if a given object implements the FinancialResultCompositionReportEntity interface.
 */
export function instanceOfFinancialResultCompositionReportEntity(value: object): value is FinancialResultCompositionReportEntity {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function FinancialResultCompositionReportEntityFromJSON(json: any): FinancialResultCompositionReportEntity {
    return FinancialResultCompositionReportEntityFromJSONTyped(json, false);
}

export function FinancialResultCompositionReportEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialResultCompositionReportEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'generatedAt': json['generatedAt'],
        'data': FinancialResultCompositionReportEntityDataFromJSON(json['data']),
    };
}

export function FinancialResultCompositionReportEntityToJSON(json: any): FinancialResultCompositionReportEntity {
    return FinancialResultCompositionReportEntityToJSONTyped(json, false);
}

export function FinancialResultCompositionReportEntityToJSONTyped(value?: FinancialResultCompositionReportEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'generatedAt': value['generatedAt'],
        'data': FinancialResultCompositionReportEntityDataToJSON(value['data']),
    };
}

