/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner
 */
export interface FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner {
    /**
     * Nome da subcategoria
     * @type {string}
     * @memberof FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner
     */
    name: string;
    /**
     * Valor da subcategoria
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner
     */
    amount: number;
}

/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner(value: object): value is FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON(json: any): FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner {
    return FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'amount': json['amount'],
    };
}

export function FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON(json: any): FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner {
    return FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSONTyped(value?: FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'amount': value['amount'],
    };
}

