/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner } from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';
import {
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';

/**
 * Despesas de vendas e marketing
 * @export
 * @interface FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses
 */
export interface FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses {
    /**
     * Valor da categoria
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses
     */
    amount: number;
    /**
     * Direção da categoria
     * @type {string}
     * @memberof FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses
     */
    direction: FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesDirectionEnum;
    /**
     * Subcategorias da categoria
     * @type {Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>}
     * @memberof FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses
     */
    subcategories: Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>;
}


/**
 * @export
 */
export const FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesDirectionEnum = typeof FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesDirectionEnum[keyof typeof FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesDirectionEnum];


/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses(value: object): value is FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('subcategories' in value) || value['subcategories'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesFromJSON(json: any): FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses {
    return FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'direction': json['direction'],
        'subcategories': ((json['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON)),
    };
}

export function FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesToJSON(json: any): FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses {
    return FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesToJSONTyped(value?: FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'direction': value['direction'],
        'subcategories': ((value['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON)),
    };
}

