/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner } from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';
import {
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';

/**
 * Outras receitas
 * @export
 * @interface FinancialStatementReportEntityDataDataInnerOtherIncome
 */
export interface FinancialStatementReportEntityDataDataInnerOtherIncome {
    /**
     * Valor da categoria
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerOtherIncome
     */
    amount: number;
    /**
     * Direção da categoria
     * @type {string}
     * @memberof FinancialStatementReportEntityDataDataInnerOtherIncome
     */
    direction: FinancialStatementReportEntityDataDataInnerOtherIncomeDirectionEnum;
    /**
     * Subcategorias da categoria
     * @type {Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>}
     * @memberof FinancialStatementReportEntityDataDataInnerOtherIncome
     */
    subcategories: Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>;
}


/**
 * @export
 */
export const FinancialStatementReportEntityDataDataInnerOtherIncomeDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type FinancialStatementReportEntityDataDataInnerOtherIncomeDirectionEnum = typeof FinancialStatementReportEntityDataDataInnerOtherIncomeDirectionEnum[keyof typeof FinancialStatementReportEntityDataDataInnerOtherIncomeDirectionEnum];


/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInnerOtherIncome interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInnerOtherIncome(value: object): value is FinancialStatementReportEntityDataDataInnerOtherIncome {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('subcategories' in value) || value['subcategories'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerOtherIncomeFromJSON(json: any): FinancialStatementReportEntityDataDataInnerOtherIncome {
    return FinancialStatementReportEntityDataDataInnerOtherIncomeFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerOtherIncomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInnerOtherIncome {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'direction': json['direction'],
        'subcategories': ((json['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON)),
    };
}

export function FinancialStatementReportEntityDataDataInnerOtherIncomeToJSON(json: any): FinancialStatementReportEntityDataDataInnerOtherIncome {
    return FinancialStatementReportEntityDataDataInnerOtherIncomeToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerOtherIncomeToJSONTyped(value?: FinancialStatementReportEntityDataDataInnerOtherIncome | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'direction': value['direction'],
        'subcategories': ((value['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON)),
    };
}

