/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FinancialStatementReportEntityDataFiltersPeriod
 */
export interface FinancialStatementReportEntityDataFiltersPeriod {
    /**
     * Data de início do período
     * @type {string}
     * @memberof FinancialStatementReportEntityDataFiltersPeriod
     */
    start: string;
    /**
     * Data de fim do período
     * @type {string}
     * @memberof FinancialStatementReportEntityDataFiltersPeriod
     */
    end: string;
}

/**
 * Check if a given object implements the FinancialStatementReportEntityDataFiltersPeriod interface.
 */
export function instanceOfFinancialStatementReportEntityDataFiltersPeriod(value: object): value is FinancialStatementReportEntityDataFiltersPeriod {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataFiltersPeriodFromJSON(json: any): FinancialStatementReportEntityDataFiltersPeriod {
    return FinancialStatementReportEntityDataFiltersPeriodFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataFiltersPeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataFiltersPeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'],
        'end': json['end'],
    };
}

export function FinancialStatementReportEntityDataFiltersPeriodToJSON(json: any): FinancialStatementReportEntityDataFiltersPeriod {
    return FinancialStatementReportEntityDataFiltersPeriodToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataFiltersPeriodToJSONTyped(value?: FinancialStatementReportEntityDataFiltersPeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'],
        'end': value['end'],
    };
}

