/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner } from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';
import {
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';

/**
 * Despesas financeiras
 * @export
 * @interface FinancialStatementReportEntityDataDataInnerFinancialExpenses
 */
export interface FinancialStatementReportEntityDataDataInnerFinancialExpenses {
    /**
     * Valor da categoria
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerFinancialExpenses
     */
    amount: number;
    /**
     * Direção da categoria
     * @type {string}
     * @memberof FinancialStatementReportEntityDataDataInnerFinancialExpenses
     */
    direction: FinancialStatementReportEntityDataDataInnerFinancialExpensesDirectionEnum;
    /**
     * Subcategorias da categoria
     * @type {Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>}
     * @memberof FinancialStatementReportEntityDataDataInnerFinancialExpenses
     */
    subcategories: Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>;
}


/**
 * @export
 */
export const FinancialStatementReportEntityDataDataInnerFinancialExpensesDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type FinancialStatementReportEntityDataDataInnerFinancialExpensesDirectionEnum = typeof FinancialStatementReportEntityDataDataInnerFinancialExpensesDirectionEnum[keyof typeof FinancialStatementReportEntityDataDataInnerFinancialExpensesDirectionEnum];


/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInnerFinancialExpenses interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInnerFinancialExpenses(value: object): value is FinancialStatementReportEntityDataDataInnerFinancialExpenses {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('subcategories' in value) || value['subcategories'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerFinancialExpensesFromJSON(json: any): FinancialStatementReportEntityDataDataInnerFinancialExpenses {
    return FinancialStatementReportEntityDataDataInnerFinancialExpensesFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerFinancialExpensesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInnerFinancialExpenses {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'direction': json['direction'],
        'subcategories': ((json['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON)),
    };
}

export function FinancialStatementReportEntityDataDataInnerFinancialExpensesToJSON(json: any): FinancialStatementReportEntityDataDataInnerFinancialExpenses {
    return FinancialStatementReportEntityDataDataInnerFinancialExpensesToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerFinancialExpensesToJSONTyped(value?: FinancialStatementReportEntityDataDataInnerFinancialExpenses | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'direction': value['direction'],
        'subcategories': ((value['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON)),
    };
}

