/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * EBITDA
 * @export
 * @interface FinancialStatementReportEntityDataDataInnerEbitda
 */
export interface FinancialStatementReportEntityDataDataInnerEbitda {
    /**
     * Valor do resultado
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerEbitda
     */
    amount: number;
    /**
     * Porcentagem do resultado
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerEbitda
     */
    percentage: number;
}

/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInnerEbitda interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInnerEbitda(value: object): value is FinancialStatementReportEntityDataDataInnerEbitda {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('percentage' in value) || value['percentage'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerEbitdaFromJSON(json: any): FinancialStatementReportEntityDataDataInnerEbitda {
    return FinancialStatementReportEntityDataDataInnerEbitdaFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerEbitdaFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInnerEbitda {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'percentage': json['percentage'],
    };
}

export function FinancialStatementReportEntityDataDataInnerEbitdaToJSON(json: any): FinancialStatementReportEntityDataDataInnerEbitda {
    return FinancialStatementReportEntityDataDataInnerEbitdaToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerEbitdaToJSONTyped(value?: FinancialStatementReportEntityDataDataInnerEbitda | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'percentage': value['percentage'],
    };
}

