/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FinancialRecordsAggregatedResultReportEntityData
 */
export interface FinancialRecordsAggregatedResultReportEntityData {
    /**
     * Sum of all INCOME financial records for the given filter in string format
     * @type {string}
     * @memberof FinancialRecordsAggregatedResultReportEntityData
     */
    income: string;
    /**
     * Sum of all OUTCOME financial records for the given filter in string format
     * @type {string}
     * @memberof FinancialRecordsAggregatedResultReportEntityData
     */
    outcome: string;
    /**
     * Absolute value of the difference between income and outcome
     * @type {string}
     * @memberof FinancialRecordsAggregatedResultReportEntityData
     */
    resultAbsoluteValue: string;
    /**
     * Direction of the result (INCOME if income > outcome, OUTCOME otherwise)
     * @type {string}
     * @memberof FinancialRecordsAggregatedResultReportEntityData
     */
    resultDirection: FinancialRecordsAggregatedResultReportEntityDataResultDirectionEnum;
}


/**
 * @export
 */
export const FinancialRecordsAggregatedResultReportEntityDataResultDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type FinancialRecordsAggregatedResultReportEntityDataResultDirectionEnum = typeof FinancialRecordsAggregatedResultReportEntityDataResultDirectionEnum[keyof typeof FinancialRecordsAggregatedResultReportEntityDataResultDirectionEnum];


/**
 * Check if a given object implements the FinancialRecordsAggregatedResultReportEntityData interface.
 */
export function instanceOfFinancialRecordsAggregatedResultReportEntityData(value: object): value is FinancialRecordsAggregatedResultReportEntityData {
    if (!('income' in value) || value['income'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('resultAbsoluteValue' in value) || value['resultAbsoluteValue'] === undefined) return false;
    if (!('resultDirection' in value) || value['resultDirection'] === undefined) return false;
    return true;
}

export function FinancialRecordsAggregatedResultReportEntityDataFromJSON(json: any): FinancialRecordsAggregatedResultReportEntityData {
    return FinancialRecordsAggregatedResultReportEntityDataFromJSONTyped(json, false);
}

export function FinancialRecordsAggregatedResultReportEntityDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialRecordsAggregatedResultReportEntityData {
    if (json == null) {
        return json;
    }
    return {
        
        'income': json['income'],
        'outcome': json['outcome'],
        'resultAbsoluteValue': json['resultAbsoluteValue'],
        'resultDirection': json['resultDirection'],
    };
}

export function FinancialRecordsAggregatedResultReportEntityDataToJSON(json: any): FinancialRecordsAggregatedResultReportEntityData {
    return FinancialRecordsAggregatedResultReportEntityDataToJSONTyped(json, false);
}

export function FinancialRecordsAggregatedResultReportEntityDataToJSONTyped(value?: FinancialRecordsAggregatedResultReportEntityData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'income': value['income'],
        'outcome': value['outcome'],
        'resultAbsoluteValue': value['resultAbsoluteValue'],
        'resultDirection': value['resultDirection'],
    };
}

