/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner } from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';
import {
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';

/**
 * Receita financeira
 * @export
 * @interface FinancialStatementReportEntityDataDataInnerFinancialIncome
 */
export interface FinancialStatementReportEntityDataDataInnerFinancialIncome {
    /**
     * Valor da categoria
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerFinancialIncome
     */
    amount: number;
    /**
     * Direção da categoria
     * @type {string}
     * @memberof FinancialStatementReportEntityDataDataInnerFinancialIncome
     */
    direction: FinancialStatementReportEntityDataDataInnerFinancialIncomeDirectionEnum;
    /**
     * Subcategorias da categoria
     * @type {Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>}
     * @memberof FinancialStatementReportEntityDataDataInnerFinancialIncome
     */
    subcategories: Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>;
}


/**
 * @export
 */
export const FinancialStatementReportEntityDataDataInnerFinancialIncomeDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type FinancialStatementReportEntityDataDataInnerFinancialIncomeDirectionEnum = typeof FinancialStatementReportEntityDataDataInnerFinancialIncomeDirectionEnum[keyof typeof FinancialStatementReportEntityDataDataInnerFinancialIncomeDirectionEnum];


/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInnerFinancialIncome interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInnerFinancialIncome(value: object): value is FinancialStatementReportEntityDataDataInnerFinancialIncome {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('subcategories' in value) || value['subcategories'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerFinancialIncomeFromJSON(json: any): FinancialStatementReportEntityDataDataInnerFinancialIncome {
    return FinancialStatementReportEntityDataDataInnerFinancialIncomeFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerFinancialIncomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInnerFinancialIncome {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'direction': json['direction'],
        'subcategories': ((json['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON)),
    };
}

export function FinancialStatementReportEntityDataDataInnerFinancialIncomeToJSON(json: any): FinancialStatementReportEntityDataDataInnerFinancialIncome {
    return FinancialStatementReportEntityDataDataInnerFinancialIncomeToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerFinancialIncomeToJSONTyped(value?: FinancialStatementReportEntityDataDataInnerFinancialIncome | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'direction': value['direction'],
        'subcategories': ((value['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON)),
    };
}

