/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialStatementReportEntityDataFilters } from './FinancialStatementReportEntityDataFilters';
import {
    FinancialStatementReportEntityDataFiltersFromJSON,
    FinancialStatementReportEntityDataFiltersFromJSONTyped,
    FinancialStatementReportEntityDataFiltersToJSON,
    FinancialStatementReportEntityDataFiltersToJSONTyped,
} from './FinancialStatementReportEntityDataFilters';
import type { FinancialStatementReportEntityDataDataInner } from './FinancialStatementReportEntityDataDataInner';
import {
    FinancialStatementReportEntityDataDataInnerFromJSON,
    FinancialStatementReportEntityDataDataInnerFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerToJSON,
    FinancialStatementReportEntityDataDataInnerToJSONTyped,
} from './FinancialStatementReportEntityDataDataInner';

/**
 * 
 * @export
 * @interface FinancialStatementReportEntityData
 */
export interface FinancialStatementReportEntityData {
    /**
     * 
     * @type {FinancialStatementReportEntityDataFilters}
     * @memberof FinancialStatementReportEntityData
     */
    filters: FinancialStatementReportEntityDataFilters;
    /**
     * 
     * @type {Array<FinancialStatementReportEntityDataDataInner>}
     * @memberof FinancialStatementReportEntityData
     */
    data: Array<FinancialStatementReportEntityDataDataInner>;
}

/**
 * Check if a given object implements the FinancialStatementReportEntityData interface.
 */
export function instanceOfFinancialStatementReportEntityData(value: object): value is FinancialStatementReportEntityData {
    if (!('filters' in value) || value['filters'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataFromJSON(json: any): FinancialStatementReportEntityData {
    return FinancialStatementReportEntityDataFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityData {
    if (json == null) {
        return json;
    }
    return {
        
        'filters': FinancialStatementReportEntityDataFiltersFromJSON(json['filters']),
        'data': ((json['data'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerFromJSON)),
    };
}

export function FinancialStatementReportEntityDataToJSON(json: any): FinancialStatementReportEntityData {
    return FinancialStatementReportEntityDataToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataToJSONTyped(value?: FinancialStatementReportEntityData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filters': FinancialStatementReportEntityDataFiltersToJSON(value['filters']),
        'data': ((value['data'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerToJSON)),
    };
}

