/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialStatementReportEntityDataDataInnerIncomeTaxExpense } from './FinancialStatementReportEntityDataDataInnerIncomeTaxExpense';
import {
    FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseFromJSON,
    FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseToJSON,
    FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerIncomeTaxExpense';
import type { FinancialStatementReportEntityDataDataInnerOtherIncome } from './FinancialStatementReportEntityDataDataInnerOtherIncome';
import {
    FinancialStatementReportEntityDataDataInnerOtherIncomeFromJSON,
    FinancialStatementReportEntityDataDataInnerOtherIncomeFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerOtherIncomeToJSON,
    FinancialStatementReportEntityDataDataInnerOtherIncomeToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerOtherIncome';
import type { FinancialStatementReportEntityDataDataInnerEbitda } from './FinancialStatementReportEntityDataDataInnerEbitda';
import {
    FinancialStatementReportEntityDataDataInnerEbitdaFromJSON,
    FinancialStatementReportEntityDataDataInnerEbitdaFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerEbitdaToJSON,
    FinancialStatementReportEntityDataDataInnerEbitdaToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerEbitda';
import type { FinancialStatementReportEntityDataDataInnerInvestments } from './FinancialStatementReportEntityDataDataInnerInvestments';
import {
    FinancialStatementReportEntityDataDataInnerInvestmentsFromJSON,
    FinancialStatementReportEntityDataDataInnerInvestmentsFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerInvestmentsToJSON,
    FinancialStatementReportEntityDataDataInnerInvestmentsToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerInvestments';
import type { FinancialStatementReportEntityDataDataInnerFinancialIncome } from './FinancialStatementReportEntityDataDataInnerFinancialIncome';
import {
    FinancialStatementReportEntityDataDataInnerFinancialIncomeFromJSON,
    FinancialStatementReportEntityDataDataInnerFinancialIncomeFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerFinancialIncomeToJSON,
    FinancialStatementReportEntityDataDataInnerFinancialIncomeToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerFinancialIncome';
import type { FinancialStatementReportEntityDataDataInnerNetIncome } from './FinancialStatementReportEntityDataDataInnerNetIncome';
import {
    FinancialStatementReportEntityDataDataInnerNetIncomeFromJSON,
    FinancialStatementReportEntityDataDataInnerNetIncomeFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerNetIncomeToJSON,
    FinancialStatementReportEntityDataDataInnerNetIncomeToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerNetIncome';
import type { FinancialStatementReportEntityDataDataInnerAdministrativeExpenses } from './FinancialStatementReportEntityDataDataInnerAdministrativeExpenses';
import {
    FinancialStatementReportEntityDataDataInnerAdministrativeExpensesFromJSON,
    FinancialStatementReportEntityDataDataInnerAdministrativeExpensesFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerAdministrativeExpensesToJSON,
    FinancialStatementReportEntityDataDataInnerAdministrativeExpensesToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerAdministrativeExpenses';
import type { CashFlowReportEntityDataDataInnerPeriod } from './CashFlowReportEntityDataDataInnerPeriod';
import {
    CashFlowReportEntityDataDataInnerPeriodFromJSON,
    CashFlowReportEntityDataDataInnerPeriodFromJSONTyped,
    CashFlowReportEntityDataDataInnerPeriodToJSON,
    CashFlowReportEntityDataDataInnerPeriodToJSONTyped,
} from './CashFlowReportEntityDataDataInnerPeriod';
import type { FinancialStatementReportEntityDataDataInnerOperationalRevenue } from './FinancialStatementReportEntityDataDataInnerOperationalRevenue';
import {
    FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerOperationalRevenue';
import type { FinancialStatementReportEntityDataDataInnerContributionMargin } from './FinancialStatementReportEntityDataDataInnerContributionMargin';
import {
    FinancialStatementReportEntityDataDataInnerContributionMarginFromJSON,
    FinancialStatementReportEntityDataDataInnerContributionMarginFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerContributionMarginToJSON,
    FinancialStatementReportEntityDataDataInnerContributionMarginToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerContributionMargin';
import type { FinancialStatementReportEntityDataDataInnerFinancialExpenses } from './FinancialStatementReportEntityDataDataInnerFinancialExpenses';
import {
    FinancialStatementReportEntityDataDataInnerFinancialExpensesFromJSON,
    FinancialStatementReportEntityDataDataInnerFinancialExpensesFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerFinancialExpensesToJSON,
    FinancialStatementReportEntityDataDataInnerFinancialExpensesToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerFinancialExpenses';
import type { FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses } from './FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses';
import {
    FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesFromJSON,
    FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesToJSON,
    FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses';
import type { FinancialStatementReportEntityDataDataInnerOperatingExpenses } from './FinancialStatementReportEntityDataDataInnerOperatingExpenses';
import {
    FinancialStatementReportEntityDataDataInnerOperatingExpensesFromJSON,
    FinancialStatementReportEntityDataDataInnerOperatingExpensesFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerOperatingExpensesToJSON,
    FinancialStatementReportEntityDataDataInnerOperatingExpensesToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerOperatingExpenses';
import type { FinancialStatementReportEntityDataDataInnerPersonnelExpenses } from './FinancialStatementReportEntityDataDataInnerPersonnelExpenses';
import {
    FinancialStatementReportEntityDataDataInnerPersonnelExpensesFromJSON,
    FinancialStatementReportEntityDataDataInnerPersonnelExpensesFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerPersonnelExpensesToJSON,
    FinancialStatementReportEntityDataDataInnerPersonnelExpensesToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerPersonnelExpenses';

/**
 * 
 * @export
 * @interface FinancialStatementReportEntityDataDataInner
 */
export interface FinancialStatementReportEntityDataDataInner {
    /**
     * 
     * @type {CashFlowReportEntityDataDataInnerPeriod}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    period: CashFlowReportEntityDataDataInnerPeriod;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerOperationalRevenue}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    operationalRevenue: FinancialStatementReportEntityDataDataInnerOperationalRevenue;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerOperatingExpenses}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    operatingExpenses: FinancialStatementReportEntityDataDataInnerOperatingExpenses;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    salesAndMarketingExpenses: FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpenses;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerAdministrativeExpenses}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    administrativeExpenses: FinancialStatementReportEntityDataDataInnerAdministrativeExpenses;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerPersonnelExpenses}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    personnelExpenses: FinancialStatementReportEntityDataDataInnerPersonnelExpenses;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerFinancialIncome}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    financialIncome: FinancialStatementReportEntityDataDataInnerFinancialIncome;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerOtherIncome}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    otherIncome: FinancialStatementReportEntityDataDataInnerOtherIncome;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerFinancialExpenses}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    financialExpenses: FinancialStatementReportEntityDataDataInnerFinancialExpenses;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerInvestments}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    investments: FinancialStatementReportEntityDataDataInnerInvestments;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerIncomeTaxExpense}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    incomeTaxExpense: FinancialStatementReportEntityDataDataInnerIncomeTaxExpense;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerContributionMargin}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    contributionMargin: FinancialStatementReportEntityDataDataInnerContributionMargin;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerNetIncome}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    netIncome: FinancialStatementReportEntityDataDataInnerNetIncome;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerEbitda}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    ebitda: FinancialStatementReportEntityDataDataInnerEbitda;
}

/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInner interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInner(value: object): value is FinancialStatementReportEntityDataDataInner {
    if (!('period' in value) || value['period'] === undefined) return false;
    if (!('operationalRevenue' in value) || value['operationalRevenue'] === undefined) return false;
    if (!('operatingExpenses' in value) || value['operatingExpenses'] === undefined) return false;
    if (!('salesAndMarketingExpenses' in value) || value['salesAndMarketingExpenses'] === undefined) return false;
    if (!('administrativeExpenses' in value) || value['administrativeExpenses'] === undefined) return false;
    if (!('personnelExpenses' in value) || value['personnelExpenses'] === undefined) return false;
    if (!('financialIncome' in value) || value['financialIncome'] === undefined) return false;
    if (!('otherIncome' in value) || value['otherIncome'] === undefined) return false;
    if (!('financialExpenses' in value) || value['financialExpenses'] === undefined) return false;
    if (!('investments' in value) || value['investments'] === undefined) return false;
    if (!('incomeTaxExpense' in value) || value['incomeTaxExpense'] === undefined) return false;
    if (!('contributionMargin' in value) || value['contributionMargin'] === undefined) return false;
    if (!('netIncome' in value) || value['netIncome'] === undefined) return false;
    if (!('ebitda' in value) || value['ebitda'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerFromJSON(json: any): FinancialStatementReportEntityDataDataInner {
    return FinancialStatementReportEntityDataDataInnerFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'period': CashFlowReportEntityDataDataInnerPeriodFromJSON(json['period']),
        'operationalRevenue': FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSON(json['operationalRevenue']),
        'operatingExpenses': FinancialStatementReportEntityDataDataInnerOperatingExpensesFromJSON(json['operatingExpenses']),
        'salesAndMarketingExpenses': FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesFromJSON(json['salesAndMarketingExpenses']),
        'administrativeExpenses': FinancialStatementReportEntityDataDataInnerAdministrativeExpensesFromJSON(json['administrativeExpenses']),
        'personnelExpenses': FinancialStatementReportEntityDataDataInnerPersonnelExpensesFromJSON(json['personnelExpenses']),
        'financialIncome': FinancialStatementReportEntityDataDataInnerFinancialIncomeFromJSON(json['financialIncome']),
        'otherIncome': FinancialStatementReportEntityDataDataInnerOtherIncomeFromJSON(json['otherIncome']),
        'financialExpenses': FinancialStatementReportEntityDataDataInnerFinancialExpensesFromJSON(json['financialExpenses']),
        'investments': FinancialStatementReportEntityDataDataInnerInvestmentsFromJSON(json['investments']),
        'incomeTaxExpense': FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseFromJSON(json['incomeTaxExpense']),
        'contributionMargin': FinancialStatementReportEntityDataDataInnerContributionMarginFromJSON(json['contributionMargin']),
        'netIncome': FinancialStatementReportEntityDataDataInnerNetIncomeFromJSON(json['netIncome']),
        'ebitda': FinancialStatementReportEntityDataDataInnerEbitdaFromJSON(json['ebitda']),
    };
}

export function FinancialStatementReportEntityDataDataInnerToJSON(json: any): FinancialStatementReportEntityDataDataInner {
    return FinancialStatementReportEntityDataDataInnerToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerToJSONTyped(value?: FinancialStatementReportEntityDataDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'period': CashFlowReportEntityDataDataInnerPeriodToJSON(value['period']),
        'operationalRevenue': FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSON(value['operationalRevenue']),
        'operatingExpenses': FinancialStatementReportEntityDataDataInnerOperatingExpensesToJSON(value['operatingExpenses']),
        'salesAndMarketingExpenses': FinancialStatementReportEntityDataDataInnerSalesAndMarketingExpensesToJSON(value['salesAndMarketingExpenses']),
        'administrativeExpenses': FinancialStatementReportEntityDataDataInnerAdministrativeExpensesToJSON(value['administrativeExpenses']),
        'personnelExpenses': FinancialStatementReportEntityDataDataInnerPersonnelExpensesToJSON(value['personnelExpenses']),
        'financialIncome': FinancialStatementReportEntityDataDataInnerFinancialIncomeToJSON(value['financialIncome']),
        'otherIncome': FinancialStatementReportEntityDataDataInnerOtherIncomeToJSON(value['otherIncome']),
        'financialExpenses': FinancialStatementReportEntityDataDataInnerFinancialExpensesToJSON(value['financialExpenses']),
        'investments': FinancialStatementReportEntityDataDataInnerInvestmentsToJSON(value['investments']),
        'incomeTaxExpense': FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseToJSON(value['incomeTaxExpense']),
        'contributionMargin': FinancialStatementReportEntityDataDataInnerContributionMarginToJSON(value['contributionMargin']),
        'netIncome': FinancialStatementReportEntityDataDataInnerNetIncomeToJSON(value['netIncome']),
        'ebitda': FinancialStatementReportEntityDataDataInnerEbitdaToJSON(value['ebitda']),
    };
}

