/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner } from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';
import {
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';

/**
 * Despesas administrativas
 * @export
 * @interface FinancialStatementReportEntityDataDataInnerAdministrativeExpenses
 */
export interface FinancialStatementReportEntityDataDataInnerAdministrativeExpenses {
    /**
     * Valor da categoria
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerAdministrativeExpenses
     */
    amount: number;
    /**
     * Direção da categoria
     * @type {string}
     * @memberof FinancialStatementReportEntityDataDataInnerAdministrativeExpenses
     */
    direction: FinancialStatementReportEntityDataDataInnerAdministrativeExpensesDirectionEnum;
    /**
     * Subcategorias da categoria
     * @type {Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>}
     * @memberof FinancialStatementReportEntityDataDataInnerAdministrativeExpenses
     */
    subcategories: Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>;
}


/**
 * @export
 */
export const FinancialStatementReportEntityDataDataInnerAdministrativeExpensesDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type FinancialStatementReportEntityDataDataInnerAdministrativeExpensesDirectionEnum = typeof FinancialStatementReportEntityDataDataInnerAdministrativeExpensesDirectionEnum[keyof typeof FinancialStatementReportEntityDataDataInnerAdministrativeExpensesDirectionEnum];


/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInnerAdministrativeExpenses interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInnerAdministrativeExpenses(value: object): value is FinancialStatementReportEntityDataDataInnerAdministrativeExpenses {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('subcategories' in value) || value['subcategories'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerAdministrativeExpensesFromJSON(json: any): FinancialStatementReportEntityDataDataInnerAdministrativeExpenses {
    return FinancialStatementReportEntityDataDataInnerAdministrativeExpensesFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerAdministrativeExpensesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInnerAdministrativeExpenses {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'direction': json['direction'],
        'subcategories': ((json['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON)),
    };
}

export function FinancialStatementReportEntityDataDataInnerAdministrativeExpensesToJSON(json: any): FinancialStatementReportEntityDataDataInnerAdministrativeExpenses {
    return FinancialStatementReportEntityDataDataInnerAdministrativeExpensesToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerAdministrativeExpensesToJSONTyped(value?: FinancialStatementReportEntityDataDataInnerAdministrativeExpenses | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'direction': value['direction'],
        'subcategories': ((value['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON)),
    };
}

