/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FinancialStatementReportEntityDataDataInnerContributionMargin
 */
export interface FinancialStatementReportEntityDataDataInnerContributionMargin {
    /**
     * Valor do resultado
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerContributionMargin
     */
    amount: number;
    /**
     * Porcentagem do resultado
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerContributionMargin
     */
    percentage: number;
}

/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInnerContributionMargin interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInnerContributionMargin(value: object): value is FinancialStatementReportEntityDataDataInnerContributionMargin {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('percentage' in value) || value['percentage'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerContributionMarginFromJSON(json: any): FinancialStatementReportEntityDataDataInnerContributionMargin {
    return FinancialStatementReportEntityDataDataInnerContributionMarginFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerContributionMarginFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInnerContributionMargin {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'percentage': json['percentage'],
    };
}

export function FinancialStatementReportEntityDataDataInnerContributionMarginToJSON(json: any): FinancialStatementReportEntityDataDataInnerContributionMargin {
    return FinancialStatementReportEntityDataDataInnerContributionMarginToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerContributionMarginToJSONTyped(value?: FinancialStatementReportEntityDataDataInnerContributionMargin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'percentage': value['percentage'],
    };
}

