/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FinancialStatementReportEntityDataDataInnerPeriod
 */
export interface FinancialStatementReportEntityDataDataInnerPeriod {
    /**
     * Data de início do período
     * @type {string}
     * @memberof FinancialStatementReportEntityDataDataInnerPeriod
     */
    start: string;
    /**
     * Data de fim do período
     * @type {string}
     * @memberof FinancialStatementReportEntityDataDataInnerPeriod
     */
    end: string;
    /**
     * Nome do período
     * @type {string}
     * @memberof FinancialStatementReportEntityDataDataInnerPeriod
     */
    name: string;
}

/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInnerPeriod interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInnerPeriod(value: object): value is FinancialStatementReportEntityDataDataInnerPeriod {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerPeriodFromJSON(json: any): FinancialStatementReportEntityDataDataInnerPeriod {
    return FinancialStatementReportEntityDataDataInnerPeriodFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerPeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInnerPeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'],
        'end': json['end'],
        'name': json['name'],
    };
}

export function FinancialStatementReportEntityDataDataInnerPeriodToJSON(json: any): FinancialStatementReportEntityDataDataInnerPeriod {
    return FinancialStatementReportEntityDataDataInnerPeriodToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerPeriodToJSONTyped(value?: FinancialStatementReportEntityDataDataInnerPeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'],
        'end': value['end'],
        'name': value['name'],
    };
}

