/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner } from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';
import {
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';

/**
 * Investimentos
 * @export
 * @interface FinancialStatementReportEntityDataDataInnerInvestments
 */
export interface FinancialStatementReportEntityDataDataInnerInvestments {
    /**
     * Valor da categoria
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerInvestments
     */
    amount: number;
    /**
     * Direção da categoria
     * @type {string}
     * @memberof FinancialStatementReportEntityDataDataInnerInvestments
     */
    direction: FinancialStatementReportEntityDataDataInnerInvestmentsDirectionEnum;
    /**
     * Subcategorias da categoria
     * @type {Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>}
     * @memberof FinancialStatementReportEntityDataDataInnerInvestments
     */
    subcategories: Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>;
}


/**
 * @export
 */
export const FinancialStatementReportEntityDataDataInnerInvestmentsDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type FinancialStatementReportEntityDataDataInnerInvestmentsDirectionEnum = typeof FinancialStatementReportEntityDataDataInnerInvestmentsDirectionEnum[keyof typeof FinancialStatementReportEntityDataDataInnerInvestmentsDirectionEnum];


/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInnerInvestments interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInnerInvestments(value: object): value is FinancialStatementReportEntityDataDataInnerInvestments {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('subcategories' in value) || value['subcategories'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerInvestmentsFromJSON(json: any): FinancialStatementReportEntityDataDataInnerInvestments {
    return FinancialStatementReportEntityDataDataInnerInvestmentsFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerInvestmentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInnerInvestments {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'direction': json['direction'],
        'subcategories': ((json['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON)),
    };
}

export function FinancialStatementReportEntityDataDataInnerInvestmentsToJSON(json: any): FinancialStatementReportEntityDataDataInnerInvestments {
    return FinancialStatementReportEntityDataDataInnerInvestmentsToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerInvestmentsToJSONTyped(value?: FinancialStatementReportEntityDataDataInnerInvestments | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'direction': value['direction'],
        'subcategories': ((value['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON)),
    };
}

