/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner } from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';
import {
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';

/**
 * 
 * @export
 * @interface FinancialStatementReportEntityDataDataInnerOperationalRevenue
 */
export interface FinancialStatementReportEntityDataDataInnerOperationalRevenue {
    /**
     * Valor da categoria
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerOperationalRevenue
     */
    amount: number;
    /**
     * Direção da categoria
     * @type {string}
     * @memberof FinancialStatementReportEntityDataDataInnerOperationalRevenue
     */
    direction: FinancialStatementReportEntityDataDataInnerOperationalRevenueDirectionEnum;
    /**
     * Subcategorias da categoria
     * @type {Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>}
     * @memberof FinancialStatementReportEntityDataDataInnerOperationalRevenue
     */
    subcategories: Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>;
}


/**
 * @export
 */
export const FinancialStatementReportEntityDataDataInnerOperationalRevenueDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type FinancialStatementReportEntityDataDataInnerOperationalRevenueDirectionEnum = typeof FinancialStatementReportEntityDataDataInnerOperationalRevenueDirectionEnum[keyof typeof FinancialStatementReportEntityDataDataInnerOperationalRevenueDirectionEnum];


/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInnerOperationalRevenue interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInnerOperationalRevenue(value: object): value is FinancialStatementReportEntityDataDataInnerOperationalRevenue {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('subcategories' in value) || value['subcategories'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSON(json: any): FinancialStatementReportEntityDataDataInnerOperationalRevenue {
    return FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInnerOperationalRevenue {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'direction': json['direction'],
        'subcategories': ((json['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON)),
    };
}

export function FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSON(json: any): FinancialStatementReportEntityDataDataInnerOperationalRevenue {
    return FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSONTyped(value?: FinancialStatementReportEntityDataDataInnerOperationalRevenue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'direction': value['direction'],
        'subcategories': ((value['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON)),
    };
}

