/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialMeasuresReportEntityData } from './FinancialMeasuresReportEntityData';
import {
    FinancialMeasuresReportEntityDataFromJSON,
    FinancialMeasuresReportEntityDataFromJSONTyped,
    FinancialMeasuresReportEntityDataToJSON,
    FinancialMeasuresReportEntityDataToJSONTyped,
} from './FinancialMeasuresReportEntityData';

/**
 * 
 * @export
 * @interface FinancialMeasuresReportEntity
 */
export interface FinancialMeasuresReportEntity {
    /**
     * 
     * @type {string}
     * @memberof FinancialMeasuresReportEntity
     */
    type: FinancialMeasuresReportEntityTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof FinancialMeasuresReportEntity
     */
    generatedAt: any | null;
    /**
     * 
     * @type {FinancialMeasuresReportEntityData}
     * @memberof FinancialMeasuresReportEntity
     */
    data: FinancialMeasuresReportEntityData;
}


/**
 * @export
 */
export const FinancialMeasuresReportEntityTypeEnum = {
    FinancialMeasuresReport: 'FINANCIAL_MEASURES_REPORT'
} as const;
export type FinancialMeasuresReportEntityTypeEnum = typeof FinancialMeasuresReportEntityTypeEnum[keyof typeof FinancialMeasuresReportEntityTypeEnum];


/**
 * Check if a given object implements the FinancialMeasuresReportEntity interface.
 */
export function instanceOfFinancialMeasuresReportEntity(value: object): value is FinancialMeasuresReportEntity {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function FinancialMeasuresReportEntityFromJSON(json: any): FinancialMeasuresReportEntity {
    return FinancialMeasuresReportEntityFromJSONTyped(json, false);
}

export function FinancialMeasuresReportEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialMeasuresReportEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'generatedAt': json['generatedAt'],
        'data': FinancialMeasuresReportEntityDataFromJSON(json['data']),
    };
}

export function FinancialMeasuresReportEntityToJSON(json: any): FinancialMeasuresReportEntity {
    return FinancialMeasuresReportEntityToJSONTyped(json, false);
}

export function FinancialMeasuresReportEntityToJSONTyped(value?: FinancialMeasuresReportEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'generatedAt': value['generatedAt'],
        'data': FinancialMeasuresReportEntityDataToJSON(value['data']),
    };
}

