/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner } from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';
import {
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';

/**
 * Despesas de pessoal
 * @export
 * @interface FinancialStatementReportEntityDataDataInnerPersonnelExpenses
 */
export interface FinancialStatementReportEntityDataDataInnerPersonnelExpenses {
    /**
     * Valor da categoria
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerPersonnelExpenses
     */
    amount: number;
    /**
     * Direção da categoria
     * @type {string}
     * @memberof FinancialStatementReportEntityDataDataInnerPersonnelExpenses
     */
    direction: FinancialStatementReportEntityDataDataInnerPersonnelExpensesDirectionEnum;
    /**
     * Subcategorias da categoria
     * @type {Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>}
     * @memberof FinancialStatementReportEntityDataDataInnerPersonnelExpenses
     */
    subcategories: Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>;
}


/**
 * @export
 */
export const FinancialStatementReportEntityDataDataInnerPersonnelExpensesDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type FinancialStatementReportEntityDataDataInnerPersonnelExpensesDirectionEnum = typeof FinancialStatementReportEntityDataDataInnerPersonnelExpensesDirectionEnum[keyof typeof FinancialStatementReportEntityDataDataInnerPersonnelExpensesDirectionEnum];


/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInnerPersonnelExpenses interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInnerPersonnelExpenses(value: object): value is FinancialStatementReportEntityDataDataInnerPersonnelExpenses {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('subcategories' in value) || value['subcategories'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerPersonnelExpensesFromJSON(json: any): FinancialStatementReportEntityDataDataInnerPersonnelExpenses {
    return FinancialStatementReportEntityDataDataInnerPersonnelExpensesFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerPersonnelExpensesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInnerPersonnelExpenses {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'direction': json['direction'],
        'subcategories': ((json['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON)),
    };
}

export function FinancialStatementReportEntityDataDataInnerPersonnelExpensesToJSON(json: any): FinancialStatementReportEntityDataDataInnerPersonnelExpenses {
    return FinancialStatementReportEntityDataDataInnerPersonnelExpensesToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerPersonnelExpensesToJSONTyped(value?: FinancialStatementReportEntityDataDataInnerPersonnelExpenses | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'direction': value['direction'],
        'subcategories': ((value['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON)),
    };
}

