/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialRecordsAggregatedResultReportEntityData } from './FinancialRecordsAggregatedResultReportEntityData';
import {
    FinancialRecordsAggregatedResultReportEntityDataFromJSON,
    FinancialRecordsAggregatedResultReportEntityDataFromJSONTyped,
    FinancialRecordsAggregatedResultReportEntityDataToJSON,
    FinancialRecordsAggregatedResultReportEntityDataToJSONTyped,
} from './FinancialRecordsAggregatedResultReportEntityData';

/**
 * 
 * @export
 * @interface FinancialRecordsAggregatedResultReportEntity
 */
export interface FinancialRecordsAggregatedResultReportEntity {
    /**
     * 
     * @type {string}
     * @memberof FinancialRecordsAggregatedResultReportEntity
     */
    type: FinancialRecordsAggregatedResultReportEntityTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof FinancialRecordsAggregatedResultReportEntity
     */
    generatedAt: any | null;
    /**
     * 
     * @type {FinancialRecordsAggregatedResultReportEntityData}
     * @memberof FinancialRecordsAggregatedResultReportEntity
     */
    data: FinancialRecordsAggregatedResultReportEntityData;
}


/**
 * @export
 */
export const FinancialRecordsAggregatedResultReportEntityTypeEnum = {
    FinancialRecordsAggregateResultReport: 'FINANCIAL_RECORDS_AGGREGATE_RESULT_REPORT',
    FinancialRecordsByContactsReport: 'FINANCIAL_RECORDS_BY_CONTACTS_REPORT',
    BankAccountsCurrentBalanceReport: 'BANK_ACCOUNTS_CURRENT_BALANCE_REPORT',
    CashFlowReport: 'CASH_FLOW_REPORT',
    FinancialStatementReport: 'FINANCIAL_STATEMENT_REPORT',
    AggregatedFinancialRecordsReport: 'AGGREGATED_FINANCIAL_RECORDS_REPORT',
    MonthlyFinancialReport: 'MONTHLY_FINANCIAL_REPORT',
    FinancialMeasuresReport: 'FINANCIAL_MEASURES_REPORT',
    FinancialResultCompositionReport: 'FINANCIAL_RESULT_COMPOSITION_REPORT',
    BankAccountsDashboardReport: 'BANK_ACCOUNTS_DASHBOARD_REPORT'
} as const;
export type FinancialRecordsAggregatedResultReportEntityTypeEnum = typeof FinancialRecordsAggregatedResultReportEntityTypeEnum[keyof typeof FinancialRecordsAggregatedResultReportEntityTypeEnum];


/**
 * Check if a given object implements the FinancialRecordsAggregatedResultReportEntity interface.
 */
export function instanceOfFinancialRecordsAggregatedResultReportEntity(value: object): value is FinancialRecordsAggregatedResultReportEntity {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function FinancialRecordsAggregatedResultReportEntityFromJSON(json: any): FinancialRecordsAggregatedResultReportEntity {
    return FinancialRecordsAggregatedResultReportEntityFromJSONTyped(json, false);
}

export function FinancialRecordsAggregatedResultReportEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialRecordsAggregatedResultReportEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'generatedAt': json['generatedAt'],
        'data': FinancialRecordsAggregatedResultReportEntityDataFromJSON(json['data']),
    };
}

export function FinancialRecordsAggregatedResultReportEntityToJSON(json: any): FinancialRecordsAggregatedResultReportEntity {
    return FinancialRecordsAggregatedResultReportEntityToJSONTyped(json, false);
}

export function FinancialRecordsAggregatedResultReportEntityToJSONTyped(value?: FinancialRecordsAggregatedResultReportEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'generatedAt': value['generatedAt'],
        'data': FinancialRecordsAggregatedResultReportEntityDataToJSON(value['data']),
    };
}

