/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner } from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';
import {
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';

/**
 * Despesa com imposto de renda
 * @export
 * @interface FinancialStatementReportEntityDataDataInnerIncomeTaxExpense
 */
export interface FinancialStatementReportEntityDataDataInnerIncomeTaxExpense {
    /**
     * Valor da categoria
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerIncomeTaxExpense
     */
    amount: number;
    /**
     * Direção da categoria
     * @type {string}
     * @memberof FinancialStatementReportEntityDataDataInnerIncomeTaxExpense
     */
    direction: FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseDirectionEnum;
    /**
     * Subcategorias da categoria
     * @type {Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>}
     * @memberof FinancialStatementReportEntityDataDataInnerIncomeTaxExpense
     */
    subcategories: Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>;
}


/**
 * @export
 */
export const FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseDirectionEnum = typeof FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseDirectionEnum[keyof typeof FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseDirectionEnum];


/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInnerIncomeTaxExpense interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInnerIncomeTaxExpense(value: object): value is FinancialStatementReportEntityDataDataInnerIncomeTaxExpense {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('subcategories' in value) || value['subcategories'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseFromJSON(json: any): FinancialStatementReportEntityDataDataInnerIncomeTaxExpense {
    return FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInnerIncomeTaxExpense {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'direction': json['direction'],
        'subcategories': ((json['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON)),
    };
}

export function FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseToJSON(json: any): FinancialStatementReportEntityDataDataInnerIncomeTaxExpense {
    return FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerIncomeTaxExpenseToJSONTyped(value?: FinancialStatementReportEntityDataDataInnerIncomeTaxExpense | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'direction': value['direction'],
        'subcategories': ((value['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON)),
    };
}

