/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialStatementReportEntityDataDataInnerPeriod } from './FinancialStatementReportEntityDataDataInnerPeriod';
import {
    FinancialStatementReportEntityDataDataInnerPeriodFromJSON,
    FinancialStatementReportEntityDataDataInnerPeriodFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerPeriodToJSON,
    FinancialStatementReportEntityDataDataInnerPeriodToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerPeriod';
import type { FinancialStatementReportEntityDataDataInnerOperationalRevenue } from './FinancialStatementReportEntityDataDataInnerOperationalRevenue';
import {
    FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerOperationalRevenue';
import type { FinancialStatementReportEntityDataDataInnerContributionMargin } from './FinancialStatementReportEntityDataDataInnerContributionMargin';
import {
    FinancialStatementReportEntityDataDataInnerContributionMarginFromJSON,
    FinancialStatementReportEntityDataDataInnerContributionMarginFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerContributionMarginToJSON,
    FinancialStatementReportEntityDataDataInnerContributionMarginToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerContributionMargin';

/**
 * 
 * @export
 * @interface FinancialStatementReportEntityDataDataInner
 */
export interface FinancialStatementReportEntityDataDataInner {
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerPeriod}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    period: FinancialStatementReportEntityDataDataInnerPeriod;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerOperationalRevenue}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    operationalRevenue: FinancialStatementReportEntityDataDataInnerOperationalRevenue;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerOperationalRevenue}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    operatingExpenses: FinancialStatementReportEntityDataDataInnerOperationalRevenue;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerOperationalRevenue}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    salesAndMarketingExpenses: FinancialStatementReportEntityDataDataInnerOperationalRevenue;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerOperationalRevenue}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    administrativeExpenses: FinancialStatementReportEntityDataDataInnerOperationalRevenue;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerOperationalRevenue}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    personnelExpenses: FinancialStatementReportEntityDataDataInnerOperationalRevenue;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerOperationalRevenue}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    financialIncome: FinancialStatementReportEntityDataDataInnerOperationalRevenue;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerOperationalRevenue}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    otherIncome: FinancialStatementReportEntityDataDataInnerOperationalRevenue;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerOperationalRevenue}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    financialExpenses: FinancialStatementReportEntityDataDataInnerOperationalRevenue;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerOperationalRevenue}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    investments: FinancialStatementReportEntityDataDataInnerOperationalRevenue;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerOperationalRevenue}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    incomeTaxExpense: FinancialStatementReportEntityDataDataInnerOperationalRevenue;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerContributionMargin}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    contributionMargin: FinancialStatementReportEntityDataDataInnerContributionMargin;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerContributionMargin}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    netIncome: FinancialStatementReportEntityDataDataInnerContributionMargin;
    /**
     * 
     * @type {FinancialStatementReportEntityDataDataInnerContributionMargin}
     * @memberof FinancialStatementReportEntityDataDataInner
     */
    ebitda: FinancialStatementReportEntityDataDataInnerContributionMargin;
}

/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInner interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInner(value: object): value is FinancialStatementReportEntityDataDataInner {
    if (!('period' in value) || value['period'] === undefined) return false;
    if (!('operationalRevenue' in value) || value['operationalRevenue'] === undefined) return false;
    if (!('operatingExpenses' in value) || value['operatingExpenses'] === undefined) return false;
    if (!('salesAndMarketingExpenses' in value) || value['salesAndMarketingExpenses'] === undefined) return false;
    if (!('administrativeExpenses' in value) || value['administrativeExpenses'] === undefined) return false;
    if (!('personnelExpenses' in value) || value['personnelExpenses'] === undefined) return false;
    if (!('financialIncome' in value) || value['financialIncome'] === undefined) return false;
    if (!('otherIncome' in value) || value['otherIncome'] === undefined) return false;
    if (!('financialExpenses' in value) || value['financialExpenses'] === undefined) return false;
    if (!('investments' in value) || value['investments'] === undefined) return false;
    if (!('incomeTaxExpense' in value) || value['incomeTaxExpense'] === undefined) return false;
    if (!('contributionMargin' in value) || value['contributionMargin'] === undefined) return false;
    if (!('netIncome' in value) || value['netIncome'] === undefined) return false;
    if (!('ebitda' in value) || value['ebitda'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerFromJSON(json: any): FinancialStatementReportEntityDataDataInner {
    return FinancialStatementReportEntityDataDataInnerFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'period': FinancialStatementReportEntityDataDataInnerPeriodFromJSON(json['period']),
        'operationalRevenue': FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSON(json['operationalRevenue']),
        'operatingExpenses': FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSON(json['operatingExpenses']),
        'salesAndMarketingExpenses': FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSON(json['salesAndMarketingExpenses']),
        'administrativeExpenses': FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSON(json['administrativeExpenses']),
        'personnelExpenses': FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSON(json['personnelExpenses']),
        'financialIncome': FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSON(json['financialIncome']),
        'otherIncome': FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSON(json['otherIncome']),
        'financialExpenses': FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSON(json['financialExpenses']),
        'investments': FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSON(json['investments']),
        'incomeTaxExpense': FinancialStatementReportEntityDataDataInnerOperationalRevenueFromJSON(json['incomeTaxExpense']),
        'contributionMargin': FinancialStatementReportEntityDataDataInnerContributionMarginFromJSON(json['contributionMargin']),
        'netIncome': FinancialStatementReportEntityDataDataInnerContributionMarginFromJSON(json['netIncome']),
        'ebitda': FinancialStatementReportEntityDataDataInnerContributionMarginFromJSON(json['ebitda']),
    };
}

export function FinancialStatementReportEntityDataDataInnerToJSON(json: any): FinancialStatementReportEntityDataDataInner {
    return FinancialStatementReportEntityDataDataInnerToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerToJSONTyped(value?: FinancialStatementReportEntityDataDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'period': FinancialStatementReportEntityDataDataInnerPeriodToJSON(value['period']),
        'operationalRevenue': FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSON(value['operationalRevenue']),
        'operatingExpenses': FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSON(value['operatingExpenses']),
        'salesAndMarketingExpenses': FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSON(value['salesAndMarketingExpenses']),
        'administrativeExpenses': FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSON(value['administrativeExpenses']),
        'personnelExpenses': FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSON(value['personnelExpenses']),
        'financialIncome': FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSON(value['financialIncome']),
        'otherIncome': FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSON(value['otherIncome']),
        'financialExpenses': FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSON(value['financialExpenses']),
        'investments': FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSON(value['investments']),
        'incomeTaxExpense': FinancialStatementReportEntityDataDataInnerOperationalRevenueToJSON(value['incomeTaxExpense']),
        'contributionMargin': FinancialStatementReportEntityDataDataInnerContributionMarginToJSON(value['contributionMargin']),
        'netIncome': FinancialStatementReportEntityDataDataInnerContributionMarginToJSON(value['netIncome']),
        'ebitda': FinancialStatementReportEntityDataDataInnerContributionMarginToJSON(value['ebitda']),
    };
}

