/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonthlyFinancialReportEntityDataFilters } from './MonthlyFinancialReportEntityDataFilters';
import {
    MonthlyFinancialReportEntityDataFiltersFromJSON,
    MonthlyFinancialReportEntityDataFiltersFromJSONTyped,
    MonthlyFinancialReportEntityDataFiltersToJSON,
    MonthlyFinancialReportEntityDataFiltersToJSONTyped,
} from './MonthlyFinancialReportEntityDataFilters';
import type { FinancialMeasuresReportEntityDataData } from './FinancialMeasuresReportEntityDataData';
import {
    FinancialMeasuresReportEntityDataDataFromJSON,
    FinancialMeasuresReportEntityDataDataFromJSONTyped,
    FinancialMeasuresReportEntityDataDataToJSON,
    FinancialMeasuresReportEntityDataDataToJSONTyped,
} from './FinancialMeasuresReportEntityDataData';

/**
 * 
 * @export
 * @interface FinancialMeasuresReportEntityData
 */
export interface FinancialMeasuresReportEntityData {
    /**
     * 
     * @type {MonthlyFinancialReportEntityDataFilters}
     * @memberof FinancialMeasuresReportEntityData
     */
    filters: MonthlyFinancialReportEntityDataFilters;
    /**
     * 
     * @type {FinancialMeasuresReportEntityDataData}
     * @memberof FinancialMeasuresReportEntityData
     */
    data: FinancialMeasuresReportEntityDataData;
}

/**
 * Check if a given object implements the FinancialMeasuresReportEntityData interface.
 */
export function instanceOfFinancialMeasuresReportEntityData(value: object): value is FinancialMeasuresReportEntityData {
    if (!('filters' in value) || value['filters'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function FinancialMeasuresReportEntityDataFromJSON(json: any): FinancialMeasuresReportEntityData {
    return FinancialMeasuresReportEntityDataFromJSONTyped(json, false);
}

export function FinancialMeasuresReportEntityDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialMeasuresReportEntityData {
    if (json == null) {
        return json;
    }
    return {
        
        'filters': MonthlyFinancialReportEntityDataFiltersFromJSON(json['filters']),
        'data': FinancialMeasuresReportEntityDataDataFromJSON(json['data']),
    };
}

export function FinancialMeasuresReportEntityDataToJSON(json: any): FinancialMeasuresReportEntityData {
    return FinancialMeasuresReportEntityDataToJSONTyped(json, false);
}

export function FinancialMeasuresReportEntityDataToJSONTyped(value?: FinancialMeasuresReportEntityData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filters': MonthlyFinancialReportEntityDataFiltersToJSON(value['filters']),
        'data': FinancialMeasuresReportEntityDataDataToJSON(value['data']),
    };
}

