/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner } from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';
import {
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSONTyped,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON,
    FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSONTyped,
} from './FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner';

/**
 * Despesas operacionais
 * @export
 * @interface FinancialStatementReportEntityDataDataInnerOperatingExpenses
 */
export interface FinancialStatementReportEntityDataDataInnerOperatingExpenses {
    /**
     * Valor da categoria
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerOperatingExpenses
     */
    amount: number;
    /**
     * Direção da categoria
     * @type {string}
     * @memberof FinancialStatementReportEntityDataDataInnerOperatingExpenses
     */
    direction: FinancialStatementReportEntityDataDataInnerOperatingExpensesDirectionEnum;
    /**
     * Subcategorias da categoria
     * @type {Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>}
     * @memberof FinancialStatementReportEntityDataDataInnerOperatingExpenses
     */
    subcategories: Array<FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInner>;
}


/**
 * @export
 */
export const FinancialStatementReportEntityDataDataInnerOperatingExpensesDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type FinancialStatementReportEntityDataDataInnerOperatingExpensesDirectionEnum = typeof FinancialStatementReportEntityDataDataInnerOperatingExpensesDirectionEnum[keyof typeof FinancialStatementReportEntityDataDataInnerOperatingExpensesDirectionEnum];


/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInnerOperatingExpenses interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInnerOperatingExpenses(value: object): value is FinancialStatementReportEntityDataDataInnerOperatingExpenses {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('subcategories' in value) || value['subcategories'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerOperatingExpensesFromJSON(json: any): FinancialStatementReportEntityDataDataInnerOperatingExpenses {
    return FinancialStatementReportEntityDataDataInnerOperatingExpensesFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerOperatingExpensesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInnerOperatingExpenses {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'direction': json['direction'],
        'subcategories': ((json['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerFromJSON)),
    };
}

export function FinancialStatementReportEntityDataDataInnerOperatingExpensesToJSON(json: any): FinancialStatementReportEntityDataDataInnerOperatingExpenses {
    return FinancialStatementReportEntityDataDataInnerOperatingExpensesToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerOperatingExpensesToJSONTyped(value?: FinancialStatementReportEntityDataDataInnerOperatingExpenses | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'direction': value['direction'],
        'subcategories': ((value['subcategories'] as Array<any>).map(FinancialStatementReportEntityDataDataInnerOperationalRevenueSubcategoriesInnerToJSON)),
    };
}

