/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialStatementReportEntityData } from './FinancialStatementReportEntityData';
import {
    FinancialStatementReportEntityDataFromJSON,
    FinancialStatementReportEntityDataFromJSONTyped,
    FinancialStatementReportEntityDataToJSON,
    FinancialStatementReportEntityDataToJSONTyped,
} from './FinancialStatementReportEntityData';

/**
 * 
 * @export
 * @interface FinancialStatementReportEntity
 */
export interface FinancialStatementReportEntity {
    /**
     * 
     * @type {string}
     * @memberof FinancialStatementReportEntity
     */
    type: FinancialStatementReportEntityTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof FinancialStatementReportEntity
     */
    generatedAt: any | null;
    /**
     * 
     * @type {FinancialStatementReportEntityData}
     * @memberof FinancialStatementReportEntity
     */
    data: FinancialStatementReportEntityData;
}


/**
 * @export
 */
export const FinancialStatementReportEntityTypeEnum = {
    FinancialStatementReport: 'FINANCIAL_STATEMENT_REPORT'
} as const;
export type FinancialStatementReportEntityTypeEnum = typeof FinancialStatementReportEntityTypeEnum[keyof typeof FinancialStatementReportEntityTypeEnum];


/**
 * Check if a given object implements the FinancialStatementReportEntity interface.
 */
export function instanceOfFinancialStatementReportEntity(value: object): value is FinancialStatementReportEntity {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityFromJSON(json: any): FinancialStatementReportEntity {
    return FinancialStatementReportEntityFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'generatedAt': json['generatedAt'],
        'data': FinancialStatementReportEntityDataFromJSON(json['data']),
    };
}

export function FinancialStatementReportEntityToJSON(json: any): FinancialStatementReportEntity {
    return FinancialStatementReportEntityToJSONTyped(json, false);
}

export function FinancialStatementReportEntityToJSONTyped(value?: FinancialStatementReportEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'generatedAt': value['generatedAt'],
        'data': FinancialStatementReportEntityDataToJSON(value['data']),
    };
}

