/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Lucro líquido
 * @export
 * @interface FinancialStatementReportEntityDataDataInnerNetIncome
 */
export interface FinancialStatementReportEntityDataDataInnerNetIncome {
    /**
     * Valor do resultado
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerNetIncome
     */
    amount: number;
    /**
     * Porcentagem do resultado
     * @type {number}
     * @memberof FinancialStatementReportEntityDataDataInnerNetIncome
     */
    percentage: number;
}

/**
 * Check if a given object implements the FinancialStatementReportEntityDataDataInnerNetIncome interface.
 */
export function instanceOfFinancialStatementReportEntityDataDataInnerNetIncome(value: object): value is FinancialStatementReportEntityDataDataInnerNetIncome {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('percentage' in value) || value['percentage'] === undefined) return false;
    return true;
}

export function FinancialStatementReportEntityDataDataInnerNetIncomeFromJSON(json: any): FinancialStatementReportEntityDataDataInnerNetIncome {
    return FinancialStatementReportEntityDataDataInnerNetIncomeFromJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerNetIncomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatementReportEntityDataDataInnerNetIncome {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'percentage': json['percentage'],
    };
}

export function FinancialStatementReportEntityDataDataInnerNetIncomeToJSON(json: any): FinancialStatementReportEntityDataDataInnerNetIncome {
    return FinancialStatementReportEntityDataDataInnerNetIncomeToJSONTyped(json, false);
}

export function FinancialStatementReportEntityDataDataInnerNetIncomeToJSONTyped(value?: FinancialStatementReportEntityDataDataInnerNetIncome | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'percentage': value['percentage'],
    };
}

