/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Filtros aplicados
 * @export
 * @interface MonthlyFinancialReportEntityDataFilters
 */
export interface MonthlyFinancialReportEntityDataFilters {
    /**
     * Lista de IDs de contas bancárias para filtrar.
     * @type {Array<string>}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    account?: Array<string>;
    /**
     * Valor do lançamento mínimo.
     * @type {number}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    amountFrom?: number;
    /**
     * Valor do lançamento máximo.
     * @type {number}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    amountTo?: number;
    /**
     * 
     * @type {string}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    amountType?: MonthlyFinancialReportEntityDataFiltersAmountTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    cashDateFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    cashDateTo?: string;
    /**
     * 
     * @type {string}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    competenceDateFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    competenceDateTo?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    completed?: boolean;
    /**
     * Lista de IDs de contatos para filtrar.
     * @type {Array<string>}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    contact?: Array<string>;
    /**
     * 
     * @type {any}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    createdAtFrom?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    createdAtTo?: any | null;
    /**
     * 
     * @type {string}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    direction?: MonthlyFinancialReportEntityDataFiltersDirectionEnum;
    /**
     * 
     * @type {string}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    dueDateFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    dueDateTo?: string;
    /**
     * ID da query a ser aplicada à consulta.
     * @type {string}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    queryId?: string;
    /**
     * Valor final do lançamento mínimo.
     * @type {number}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    finalAmountFrom?: number;
    /**
     * Valor final do lançamento máximo.
     * @type {number}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    finalAmountTo?: number;
    /**
     * Lista de IDs de parcelas para filtrar.
     * @type {Array<string>}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    installmentFinancialRecord?: Array<string>;
    /**
     * Lista de IDs de recorrências para filtrar.
     * @type {Array<string>}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    recurringFinancialRecord?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    reconciled?: boolean;
    /**
     * Lista de IDs de subcategorias para filtrar.
     * @type {Array<string>}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    subcategory?: Array<string>;
    /**
     * Lista de IDs de tags para filtrar.
     * @type {Array<string>}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    tags?: Array<string>;
    /**
     * Se deve considerar transferências internas nos relatórios.
     * @type {boolean}
     * @memberof MonthlyFinancialReportEntityDataFilters
     */
    considerInternalTransfers?: boolean;
}


/**
 * @export
 */
export const MonthlyFinancialReportEntityDataFiltersAmountTypeEnum = {
    Base: 'base',
    Final: 'final'
} as const;
export type MonthlyFinancialReportEntityDataFiltersAmountTypeEnum = typeof MonthlyFinancialReportEntityDataFiltersAmountTypeEnum[keyof typeof MonthlyFinancialReportEntityDataFiltersAmountTypeEnum];

/**
 * @export
 */
export const MonthlyFinancialReportEntityDataFiltersDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type MonthlyFinancialReportEntityDataFiltersDirectionEnum = typeof MonthlyFinancialReportEntityDataFiltersDirectionEnum[keyof typeof MonthlyFinancialReportEntityDataFiltersDirectionEnum];


/**
 * Check if a given object implements the MonthlyFinancialReportEntityDataFilters interface.
 */
export function instanceOfMonthlyFinancialReportEntityDataFilters(value: object): value is MonthlyFinancialReportEntityDataFilters {
    return true;
}

export function MonthlyFinancialReportEntityDataFiltersFromJSON(json: any): MonthlyFinancialReportEntityDataFilters {
    return MonthlyFinancialReportEntityDataFiltersFromJSONTyped(json, false);
}

export function MonthlyFinancialReportEntityDataFiltersFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonthlyFinancialReportEntityDataFilters {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'] == null ? undefined : json['account'],
        'amountFrom': json['amountFrom'] == null ? undefined : json['amountFrom'],
        'amountTo': json['amountTo'] == null ? undefined : json['amountTo'],
        'amountType': json['amountType'] == null ? undefined : json['amountType'],
        'cashDateFrom': json['cashDateFrom'] == null ? undefined : json['cashDateFrom'],
        'cashDateTo': json['cashDateTo'] == null ? undefined : json['cashDateTo'],
        'competenceDateFrom': json['competenceDateFrom'] == null ? undefined : json['competenceDateFrom'],
        'competenceDateTo': json['competenceDateTo'] == null ? undefined : json['competenceDateTo'],
        'completed': json['completed'] == null ? undefined : json['completed'],
        'contact': json['contact'] == null ? undefined : json['contact'],
        'createdAtFrom': json['createdAtFrom'] == null ? undefined : json['createdAtFrom'],
        'createdAtTo': json['createdAtTo'] == null ? undefined : json['createdAtTo'],
        'direction': json['direction'] == null ? undefined : json['direction'],
        'dueDateFrom': json['dueDateFrom'] == null ? undefined : json['dueDateFrom'],
        'dueDateTo': json['dueDateTo'] == null ? undefined : json['dueDateTo'],
        'queryId': json['queryId'] == null ? undefined : json['queryId'],
        'finalAmountFrom': json['finalAmountFrom'] == null ? undefined : json['finalAmountFrom'],
        'finalAmountTo': json['finalAmountTo'] == null ? undefined : json['finalAmountTo'],
        'installmentFinancialRecord': json['installmentFinancialRecord'] == null ? undefined : json['installmentFinancialRecord'],
        'recurringFinancialRecord': json['recurringFinancialRecord'] == null ? undefined : json['recurringFinancialRecord'],
        'reconciled': json['reconciled'] == null ? undefined : json['reconciled'],
        'subcategory': json['subcategory'] == null ? undefined : json['subcategory'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'considerInternalTransfers': json['considerInternalTransfers'] == null ? undefined : json['considerInternalTransfers'],
    };
}

export function MonthlyFinancialReportEntityDataFiltersToJSON(json: any): MonthlyFinancialReportEntityDataFilters {
    return MonthlyFinancialReportEntityDataFiltersToJSONTyped(json, false);
}

export function MonthlyFinancialReportEntityDataFiltersToJSONTyped(value?: MonthlyFinancialReportEntityDataFilters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': value['account'],
        'amountFrom': value['amountFrom'],
        'amountTo': value['amountTo'],
        'amountType': value['amountType'],
        'cashDateFrom': value['cashDateFrom'],
        'cashDateTo': value['cashDateTo'],
        'competenceDateFrom': value['competenceDateFrom'],
        'competenceDateTo': value['competenceDateTo'],
        'completed': value['completed'],
        'contact': value['contact'],
        'createdAtFrom': value['createdAtFrom'],
        'createdAtTo': value['createdAtTo'],
        'direction': value['direction'],
        'dueDateFrom': value['dueDateFrom'],
        'dueDateTo': value['dueDateTo'],
        'queryId': value['queryId'],
        'finalAmountFrom': value['finalAmountFrom'],
        'finalAmountTo': value['finalAmountTo'],
        'installmentFinancialRecord': value['installmentFinancialRecord'],
        'recurringFinancialRecord': value['recurringFinancialRecord'],
        'reconciled': value['reconciled'],
        'subcategory': value['subcategory'],
        'tags': value['tags'],
        'considerInternalTransfers': value['considerInternalTransfers'],
    };
}

