/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonthlyFinancialReportEntityDataFilters } from './MonthlyFinancialReportEntityDataFilters';
import {
    MonthlyFinancialReportEntityDataFiltersFromJSON,
    MonthlyFinancialReportEntityDataFiltersFromJSONTyped,
    MonthlyFinancialReportEntityDataFiltersToJSON,
    MonthlyFinancialReportEntityDataFiltersToJSONTyped,
} from './MonthlyFinancialReportEntityDataFilters';
import type { MonthlyFinancialReportEntityDataData } from './MonthlyFinancialReportEntityDataData';
import {
    MonthlyFinancialReportEntityDataDataFromJSON,
    MonthlyFinancialReportEntityDataDataFromJSONTyped,
    MonthlyFinancialReportEntityDataDataToJSON,
    MonthlyFinancialReportEntityDataDataToJSONTyped,
} from './MonthlyFinancialReportEntityDataData';

/**
 * 
 * @export
 * @interface MonthlyFinancialReportEntityData
 */
export interface MonthlyFinancialReportEntityData {
    /**
     * 
     * @type {MonthlyFinancialReportEntityDataFilters}
     * @memberof MonthlyFinancialReportEntityData
     */
    filters: MonthlyFinancialReportEntityDataFilters;
    /**
     * 
     * @type {MonthlyFinancialReportEntityDataData}
     * @memberof MonthlyFinancialReportEntityData
     */
    data: MonthlyFinancialReportEntityDataData;
}

/**
 * Check if a given object implements the MonthlyFinancialReportEntityData interface.
 */
export function instanceOfMonthlyFinancialReportEntityData(value: object): value is MonthlyFinancialReportEntityData {
    if (!('filters' in value) || value['filters'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function MonthlyFinancialReportEntityDataFromJSON(json: any): MonthlyFinancialReportEntityData {
    return MonthlyFinancialReportEntityDataFromJSONTyped(json, false);
}

export function MonthlyFinancialReportEntityDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonthlyFinancialReportEntityData {
    if (json == null) {
        return json;
    }
    return {
        
        'filters': MonthlyFinancialReportEntityDataFiltersFromJSON(json['filters']),
        'data': MonthlyFinancialReportEntityDataDataFromJSON(json['data']),
    };
}

export function MonthlyFinancialReportEntityDataToJSON(json: any): MonthlyFinancialReportEntityData {
    return MonthlyFinancialReportEntityDataToJSONTyped(json, false);
}

export function MonthlyFinancialReportEntityDataToJSONTyped(value?: MonthlyFinancialReportEntityData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filters': MonthlyFinancialReportEntityDataFiltersToJSON(value['filters']),
        'data': MonthlyFinancialReportEntityDataDataToJSON(value['data']),
    };
}

