/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MonthlyFinancialReportEntityDataDataItemsInner
 */
export interface MonthlyFinancialReportEntityDataDataItemsInner {
    /**
     * Mês no formato YYYY-MM
     * @type {string}
     * @memberof MonthlyFinancialReportEntityDataDataItemsInner
     */
    month: string;
    /**
     * Soma das receitas do mês em formato string
     * @type {number}
     * @memberof MonthlyFinancialReportEntityDataDataItemsInner
     */
    income: number;
    /**
     * Soma das despesas do mês em formato string
     * @type {number}
     * @memberof MonthlyFinancialReportEntityDataDataItemsInner
     */
    outcome: number;
}

/**
 * Check if a given object implements the MonthlyFinancialReportEntityDataDataItemsInner interface.
 */
export function instanceOfMonthlyFinancialReportEntityDataDataItemsInner(value: object): value is MonthlyFinancialReportEntityDataDataItemsInner {
    if (!('month' in value) || value['month'] === undefined) return false;
    if (!('income' in value) || value['income'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    return true;
}

export function MonthlyFinancialReportEntityDataDataItemsInnerFromJSON(json: any): MonthlyFinancialReportEntityDataDataItemsInner {
    return MonthlyFinancialReportEntityDataDataItemsInnerFromJSONTyped(json, false);
}

export function MonthlyFinancialReportEntityDataDataItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonthlyFinancialReportEntityDataDataItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'month': json['month'],
        'income': json['income'],
        'outcome': json['outcome'],
    };
}

export function MonthlyFinancialReportEntityDataDataItemsInnerToJSON(json: any): MonthlyFinancialReportEntityDataDataItemsInner {
    return MonthlyFinancialReportEntityDataDataItemsInnerToJSONTyped(json, false);
}

export function MonthlyFinancialReportEntityDataDataItemsInnerToJSONTyped(value?: MonthlyFinancialReportEntityDataDataItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'month': value['month'],
        'income': value['income'],
        'outcome': value['outcome'],
    };
}

