/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonthlyFinancialReportEntityData } from './MonthlyFinancialReportEntityData';
import {
    MonthlyFinancialReportEntityDataFromJSON,
    MonthlyFinancialReportEntityDataFromJSONTyped,
    MonthlyFinancialReportEntityDataToJSON,
    MonthlyFinancialReportEntityDataToJSONTyped,
} from './MonthlyFinancialReportEntityData';

/**
 * 
 * @export
 * @interface MonthlyFinancialReportEntity
 */
export interface MonthlyFinancialReportEntity {
    /**
     * 
     * @type {string}
     * @memberof MonthlyFinancialReportEntity
     */
    type: MonthlyFinancialReportEntityTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof MonthlyFinancialReportEntity
     */
    generatedAt: any | null;
    /**
     * 
     * @type {MonthlyFinancialReportEntityData}
     * @memberof MonthlyFinancialReportEntity
     */
    data: MonthlyFinancialReportEntityData;
}


/**
 * @export
 */
export const MonthlyFinancialReportEntityTypeEnum = {
    MonthlyFinancialReport: 'MONTHLY_FINANCIAL_REPORT'
} as const;
export type MonthlyFinancialReportEntityTypeEnum = typeof MonthlyFinancialReportEntityTypeEnum[keyof typeof MonthlyFinancialReportEntityTypeEnum];


/**
 * Check if a given object implements the MonthlyFinancialReportEntity interface.
 */
export function instanceOfMonthlyFinancialReportEntity(value: object): value is MonthlyFinancialReportEntity {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function MonthlyFinancialReportEntityFromJSON(json: any): MonthlyFinancialReportEntity {
    return MonthlyFinancialReportEntityFromJSONTyped(json, false);
}

export function MonthlyFinancialReportEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonthlyFinancialReportEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'generatedAt': json['generatedAt'],
        'data': MonthlyFinancialReportEntityDataFromJSON(json['data']),
    };
}

export function MonthlyFinancialReportEntityToJSON(json: any): MonthlyFinancialReportEntity {
    return MonthlyFinancialReportEntityToJSONTyped(json, false);
}

export function MonthlyFinancialReportEntityToJSONTyped(value?: MonthlyFinancialReportEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'generatedAt': value['generatedAt'],
        'data': MonthlyFinancialReportEntityDataToJSON(value['data']),
    };
}

