/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationBalancePerAccountEntity
 */
export interface OrganizationBalancePerAccountEntity {
    /**
     * ID da conta
     * @type {string}
     * @memberof OrganizationBalancePerAccountEntity
     */
    accountId: string;
    /**
     * Nome da conta
     * @type {string}
     * @memberof OrganizationBalancePerAccountEntity
     */
    accountName: string;
    /**
     * Tipo de conta
     * @type {string}
     * @memberof OrganizationBalancePerAccountEntity
     */
    accountType: string;
    /**
     * Tipo de conexão da conta
     * @type {string}
     * @memberof OrganizationBalancePerAccountEntity
     */
    connectionType?: string | null;
    /**
     * URL da imagem da conta
     * @type {string}
     * @memberof OrganizationBalancePerAccountEntity
     */
    accountImageUrl?: string | null;
    /**
     * Saldo atual da conta
     * @type {string}
     * @memberof OrganizationBalancePerAccountEntity
     */
    currentBalance: string;
}

/**
 * Check if a given object implements the OrganizationBalancePerAccountEntity interface.
 */
export function instanceOfOrganizationBalancePerAccountEntity(value: object): value is OrganizationBalancePerAccountEntity {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('accountName' in value) || value['accountName'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    if (!('currentBalance' in value) || value['currentBalance'] === undefined) return false;
    return true;
}

export function OrganizationBalancePerAccountEntityFromJSON(json: any): OrganizationBalancePerAccountEntity {
    return OrganizationBalancePerAccountEntityFromJSONTyped(json, false);
}

export function OrganizationBalancePerAccountEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationBalancePerAccountEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'accountName': json['accountName'],
        'accountType': json['accountType'],
        'connectionType': json['connectionType'] == null ? undefined : json['connectionType'],
        'accountImageUrl': json['accountImageUrl'] == null ? undefined : json['accountImageUrl'],
        'currentBalance': json['currentBalance'],
    };
}

export function OrganizationBalancePerAccountEntityToJSON(json: any): OrganizationBalancePerAccountEntity {
    return OrganizationBalancePerAccountEntityToJSONTyped(json, false);
}

export function OrganizationBalancePerAccountEntityToJSONTyped(value?: OrganizationBalancePerAccountEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'accountName': value['accountName'],
        'accountType': value['accountType'],
        'connectionType': value['connectionType'],
        'accountImageUrl': value['accountImageUrl'],
        'currentBalance': value['currentBalance'],
    };
}

