/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationBalanceHistoryPerAccountEntityHistoryInner } from './OrganizationBalanceHistoryPerAccountEntityHistoryInner';
import {
    OrganizationBalanceHistoryPerAccountEntityHistoryInnerFromJSON,
    OrganizationBalanceHistoryPerAccountEntityHistoryInnerFromJSONTyped,
    OrganizationBalanceHistoryPerAccountEntityHistoryInnerToJSON,
    OrganizationBalanceHistoryPerAccountEntityHistoryInnerToJSONTyped,
} from './OrganizationBalanceHistoryPerAccountEntityHistoryInner';

/**
 * 
 * @export
 * @interface OrganizationBalanceHistoryPerAccountEntity
 */
export interface OrganizationBalanceHistoryPerAccountEntity {
    /**
     * ID da conta
     * @type {string}
     * @memberof OrganizationBalanceHistoryPerAccountEntity
     */
    accountId: string;
    /**
     * Nome da conta
     * @type {string}
     * @memberof OrganizationBalanceHistoryPerAccountEntity
     */
    accountName: string;
    /**
     * Tipo de conta
     * @type {string}
     * @memberof OrganizationBalanceHistoryPerAccountEntity
     */
    accountType: string;
    /**
     * URL da imagem da conta
     * @type {string}
     * @memberof OrganizationBalanceHistoryPerAccountEntity
     */
    accountImageUrl?: string | null;
    /**
     * Tipo de conexão da conta
     * @type {string}
     * @memberof OrganizationBalanceHistoryPerAccountEntity
     */
    connectionType?: string | null;
    /**
     * Saldo atual da conta
     * @type {string}
     * @memberof OrganizationBalanceHistoryPerAccountEntity
     */
    currentBalance: string;
    /**
     * 
     * @type {Array<OrganizationBalanceHistoryPerAccountEntityHistoryInner>}
     * @memberof OrganizationBalanceHistoryPerAccountEntity
     */
    history: Array<OrganizationBalanceHistoryPerAccountEntityHistoryInner>;
}

/**
 * Check if a given object implements the OrganizationBalanceHistoryPerAccountEntity interface.
 */
export function instanceOfOrganizationBalanceHistoryPerAccountEntity(value: object): value is OrganizationBalanceHistoryPerAccountEntity {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('accountName' in value) || value['accountName'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    if (!('currentBalance' in value) || value['currentBalance'] === undefined) return false;
    if (!('history' in value) || value['history'] === undefined) return false;
    return true;
}

export function OrganizationBalanceHistoryPerAccountEntityFromJSON(json: any): OrganizationBalanceHistoryPerAccountEntity {
    return OrganizationBalanceHistoryPerAccountEntityFromJSONTyped(json, false);
}

export function OrganizationBalanceHistoryPerAccountEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationBalanceHistoryPerAccountEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'accountName': json['accountName'],
        'accountType': json['accountType'],
        'accountImageUrl': json['accountImageUrl'] == null ? undefined : json['accountImageUrl'],
        'connectionType': json['connectionType'] == null ? undefined : json['connectionType'],
        'currentBalance': json['currentBalance'],
        'history': ((json['history'] as Array<any>).map(OrganizationBalanceHistoryPerAccountEntityHistoryInnerFromJSON)),
    };
}

export function OrganizationBalanceHistoryPerAccountEntityToJSON(json: any): OrganizationBalanceHistoryPerAccountEntity {
    return OrganizationBalanceHistoryPerAccountEntityToJSONTyped(json, false);
}

export function OrganizationBalanceHistoryPerAccountEntityToJSONTyped(value?: OrganizationBalanceHistoryPerAccountEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'accountName': value['accountName'],
        'accountType': value['accountType'],
        'accountImageUrl': value['accountImageUrl'],
        'connectionType': value['connectionType'],
        'currentBalance': value['currentBalance'],
        'history': ((value['history'] as Array<any>).map(OrganizationBalanceHistoryPerAccountEntityHistoryInnerToJSON)),
    };
}

