/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashFlowReportEntityDataDataInnerPeriod } from './CashFlowReportEntityDataDataInnerPeriod';
import {
    CashFlowReportEntityDataDataInnerPeriodFromJSON,
    CashFlowReportEntityDataDataInnerPeriodFromJSONTyped,
    CashFlowReportEntityDataDataInnerPeriodToJSON,
    CashFlowReportEntityDataDataInnerPeriodToJSONTyped,
} from './CashFlowReportEntityDataDataInnerPeriod';

/**
 * 
 * @export
 * @interface OrganizationBalanceHistoryPerAccountEntityHistoryInner
 */
export interface OrganizationBalanceHistoryPerAccountEntityHistoryInner {
    /**
     * 
     * @type {CashFlowReportEntityDataDataInnerPeriod}
     * @memberof OrganizationBalanceHistoryPerAccountEntityHistoryInner
     */
    period: CashFlowReportEntityDataDataInnerPeriod;
    /**
     * Saldo inicial
     * @type {string}
     * @memberof OrganizationBalanceHistoryPerAccountEntityHistoryInner
     */
    openingBalance: string;
    /**
     * Total de receitas
     * @type {string}
     * @memberof OrganizationBalanceHistoryPerAccountEntityHistoryInner
     */
    totalIncome: string;
    /**
     * Total de despesas
     * @type {string}
     * @memberof OrganizationBalanceHistoryPerAccountEntityHistoryInner
     */
    totalOutcome: string;
    /**
     * Saldo final
     * @type {string}
     * @memberof OrganizationBalanceHistoryPerAccountEntityHistoryInner
     */
    closingBalance: string;
}

/**
 * Check if a given object implements the OrganizationBalanceHistoryPerAccountEntityHistoryInner interface.
 */
export function instanceOfOrganizationBalanceHistoryPerAccountEntityHistoryInner(value: object): value is OrganizationBalanceHistoryPerAccountEntityHistoryInner {
    if (!('period' in value) || value['period'] === undefined) return false;
    if (!('openingBalance' in value) || value['openingBalance'] === undefined) return false;
    if (!('totalIncome' in value) || value['totalIncome'] === undefined) return false;
    if (!('totalOutcome' in value) || value['totalOutcome'] === undefined) return false;
    if (!('closingBalance' in value) || value['closingBalance'] === undefined) return false;
    return true;
}

export function OrganizationBalanceHistoryPerAccountEntityHistoryInnerFromJSON(json: any): OrganizationBalanceHistoryPerAccountEntityHistoryInner {
    return OrganizationBalanceHistoryPerAccountEntityHistoryInnerFromJSONTyped(json, false);
}

export function OrganizationBalanceHistoryPerAccountEntityHistoryInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationBalanceHistoryPerAccountEntityHistoryInner {
    if (json == null) {
        return json;
    }
    return {
        
        'period': CashFlowReportEntityDataDataInnerPeriodFromJSON(json['period']),
        'openingBalance': json['openingBalance'],
        'totalIncome': json['totalIncome'],
        'totalOutcome': json['totalOutcome'],
        'closingBalance': json['closingBalance'],
    };
}

export function OrganizationBalanceHistoryPerAccountEntityHistoryInnerToJSON(json: any): OrganizationBalanceHistoryPerAccountEntityHistoryInner {
    return OrganizationBalanceHistoryPerAccountEntityHistoryInnerToJSONTyped(json, false);
}

export function OrganizationBalanceHistoryPerAccountEntityHistoryInnerToJSONTyped(value?: OrganizationBalanceHistoryPerAccountEntityHistoryInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'period': CashFlowReportEntityDataDataInnerPeriodToJSON(value['period']),
        'openingBalance': value['openingBalance'],
        'totalIncome': value['totalIncome'],
        'totalOutcome': value['totalOutcome'],
        'closingBalance': value['closingBalance'],
    };
}

