/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 1.3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectedCashFlowEntityPeriodsInnerPeriod
 */
export interface ProjectedCashFlowEntityPeriodsInnerPeriod {
    /**
     * Data de início do período
     * @type {string}
     * @memberof ProjectedCashFlowEntityPeriodsInnerPeriod
     */
    start: string;
    /**
     * Data de fim do período
     * @type {string}
     * @memberof ProjectedCashFlowEntityPeriodsInnerPeriod
     */
    end: string;
}

/**
 * Check if a given object implements the ProjectedCashFlowEntityPeriodsInnerPeriod interface.
 */
export function instanceOfProjectedCashFlowEntityPeriodsInnerPeriod(value: object): value is ProjectedCashFlowEntityPeriodsInnerPeriod {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function ProjectedCashFlowEntityPeriodsInnerPeriodFromJSON(json: any): ProjectedCashFlowEntityPeriodsInnerPeriod {
    return ProjectedCashFlowEntityPeriodsInnerPeriodFromJSONTyped(json, false);
}

export function ProjectedCashFlowEntityPeriodsInnerPeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectedCashFlowEntityPeriodsInnerPeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'],
        'end': json['end'],
    };
}

export function ProjectedCashFlowEntityPeriodsInnerPeriodToJSON(json: any): ProjectedCashFlowEntityPeriodsInnerPeriod {
    return ProjectedCashFlowEntityPeriodsInnerPeriodToJSONTyped(json, false);
}

export function ProjectedCashFlowEntityPeriodsInnerPeriodToJSONTyped(value?: ProjectedCashFlowEntityPeriodsInnerPeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'],
        'end': value['end'],
    };
}

