/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus analytics-api
 * Api do sistema Pegasus para geração de relatórios e dashboards.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectedCashFlowEntityPeriodsInner } from './ProjectedCashFlowEntityPeriodsInner';
import {
    ProjectedCashFlowEntityPeriodsInnerFromJSON,
    ProjectedCashFlowEntityPeriodsInnerFromJSONTyped,
    ProjectedCashFlowEntityPeriodsInnerToJSON,
    ProjectedCashFlowEntityPeriodsInnerToJSONTyped,
} from './ProjectedCashFlowEntityPeriodsInner';

/**
 * 
 * @export
 * @interface ProjectedCashFlowEntity
 */
export interface ProjectedCashFlowEntity {
    /**
     * Lista de períodos com fluxo de caixa projetado
     * @type {Array<ProjectedCashFlowEntityPeriodsInner>}
     * @memberof ProjectedCashFlowEntity
     */
    periods: Array<ProjectedCashFlowEntityPeriodsInner>;
}

/**
 * Check if a given object implements the ProjectedCashFlowEntity interface.
 */
export function instanceOfProjectedCashFlowEntity(value: object): value is ProjectedCashFlowEntity {
    if (!('periods' in value) || value['periods'] === undefined) return false;
    return true;
}

export function ProjectedCashFlowEntityFromJSON(json: any): ProjectedCashFlowEntity {
    return ProjectedCashFlowEntityFromJSONTyped(json, false);
}

export function ProjectedCashFlowEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectedCashFlowEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'periods': ((json['periods'] as Array<any>).map(ProjectedCashFlowEntityPeriodsInnerFromJSON)),
    };
}

export function ProjectedCashFlowEntityToJSON(json: any): ProjectedCashFlowEntity {
    return ProjectedCashFlowEntityToJSONTyped(json, false);
}

export function ProjectedCashFlowEntityToJSONTyped(value?: ProjectedCashFlowEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'periods': ((value['periods'] as Array<any>).map(ProjectedCashFlowEntityPeriodsInnerToJSON)),
    };
}

